/*
 * SPDX-FileCopyrightText: 2006-2021 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: BSD-3-Clause
 */

// Autogenerated by Thrift Compiler (0.14.1-yarped)
//
// This is an automatically generated file.
// It could get re-generated if the ALLOW_IDL_GENERATION flag is on.

#include <return_getAvailablePids.h>

// Constructor with field values
return_getAvailablePids::return_getAvailablePids(const yarp::dev::ReturnValue& ret,
                                                 const std::vector<yarp::dev::PidControlTypeEnum>& avail) :
        WirePortable(),
        ret(ret),
        avail(avail)
{
}

// Read structure on a Wire
bool return_getAvailablePids::read(yarp::os::idl::WireReader& reader)
{
    if (!nested_read_ret(reader)) {
        return false;
    }
    if (!read_avail(reader)) {
        return false;
    }
    if (reader.isError()) {
        return false;
    }
    return true;
}

// Read structure on a Connection
bool return_getAvailablePids::read(yarp::os::ConnectionReader& connection)
{
    yarp::os::idl::WireReader reader(connection);
    if (!reader.readListHeader(2)) {
        return false;
    }
    if (!read(reader)) {
        return false;
    }
    return true;
}

// Write structure on a Wire
bool return_getAvailablePids::write(const yarp::os::idl::WireWriter& writer) const
{
    if (!nested_write_ret(writer)) {
        return false;
    }
    if (!write_avail(writer)) {
        return false;
    }
    if (writer.isError()) {
        return false;
    }
    return true;
}

// Write structure on a Connection
bool return_getAvailablePids::write(yarp::os::ConnectionWriter& connection) const
{
    yarp::os::idl::WireWriter writer(connection);
    if (!writer.writeListHeader(2)) {
        return false;
    }
    if (!write(writer)) {
        return false;
    }
    return true;
}

// Convert to a printable string
std::string return_getAvailablePids::toString() const
{
    yarp::os::Bottle b;
    if (!yarp::os::Portable::copyPortable(*this, b)) {
        return {};
    }
    return b.toString();
}

// read ret field
bool return_getAvailablePids::read_ret(yarp::os::idl::WireReader& reader)
{
    if (reader.noMore()) {
        reader.fail();
        return false;
    }
    if (!reader.read(ret)) {
        reader.fail();
        return false;
    }
    return true;
}

// write ret field
bool return_getAvailablePids::write_ret(const yarp::os::idl::WireWriter& writer) const
{
    if (!writer.write(ret)) {
        return false;
    }
    return true;
}

// read (nested) ret field
bool return_getAvailablePids::nested_read_ret(yarp::os::idl::WireReader& reader)
{
    if (reader.noMore()) {
        reader.fail();
        return false;
    }
    if (!reader.readNested(ret)) {
        reader.fail();
        return false;
    }
    return true;
}

// write (nested) ret field
bool return_getAvailablePids::nested_write_ret(const yarp::os::idl::WireWriter& writer) const
{
    if (!writer.writeNested(ret)) {
        return false;
    }
    return true;
}

// read avail field
bool return_getAvailablePids::read_avail(yarp::os::idl::WireReader& reader)
{
    if (reader.noMore()) {
        reader.fail();
        return false;
    }
    size_t _csize;
    yarp::os::idl::WireState _etype;
    reader.readListBegin(_etype, _csize);
    // WireReader removes BOTTLE_TAG_LIST from the tag
    constexpr int expected_tag = ((BOTTLE_TAG_INT32) & (~BOTTLE_TAG_LIST));
    if constexpr (expected_tag != 0) {
        if (_csize != 0 && _etype.code != expected_tag) {
            return false;
        }
    }
    avail.resize(_csize);
    if (_csize != 0 && !reader.readBlock(reinterpret_cast<char*>(avail.data()), avail.size() * sizeof(yarp::dev::PidControlTypeEnum))) {
        return false;
    }
    reader.readListEnd();
    return true;
}

// write avail field
bool return_getAvailablePids::write_avail(const yarp::os::idl::WireWriter& writer) const
{
    if (!writer.writeListBegin(BOTTLE_TAG_INT32, avail.size())) {
        return false;
    }
    if (!writer.writeBlock(reinterpret_cast<const char*>(avail.data()), avail.size() * sizeof(yarp::dev::PidControlTypeEnum))) {
        return false;
    }
    if (!writer.writeListEnd()) {
        return false;
    }
    return true;
}

// read (nested) avail field
bool return_getAvailablePids::nested_read_avail(yarp::os::idl::WireReader& reader)
{
    if (reader.noMore()) {
        reader.fail();
        return false;
    }
    size_t _csize;
    yarp::os::idl::WireState _etype;
    reader.readListBegin(_etype, _csize);
    // WireReader removes BOTTLE_TAG_LIST from the tag
    constexpr int expected_tag = ((BOTTLE_TAG_INT32) & (~BOTTLE_TAG_LIST));
    if constexpr (expected_tag != 0) {
        if (_csize != 0 && _etype.code != expected_tag) {
            return false;
        }
    }
    avail.resize(_csize);
    if (_csize != 0 && !reader.readBlock(reinterpret_cast<char*>(avail.data()), avail.size() * sizeof(yarp::dev::PidControlTypeEnum))) {
        return false;
    }
    reader.readListEnd();
    return true;
}

// write (nested) avail field
bool return_getAvailablePids::nested_write_avail(const yarp::os::idl::WireWriter& writer) const
{
    if (!writer.writeListBegin(BOTTLE_TAG_INT32, avail.size())) {
        return false;
    }
    if (!writer.writeBlock(reinterpret_cast<const char*>(avail.data()), avail.size() * sizeof(yarp::dev::PidControlTypeEnum))) {
        return false;
    }
    if (!writer.writeListEnd()) {
        return false;
    }
    return true;
}
