/*
 * SPDX-FileCopyrightText: 2006-2021 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: BSD-3-Clause
 */

// Autogenerated by Thrift Compiler (0.14.1-yarped)
//
// This is an automatically generated file.
// It could get re-generated if the ALLOW_IDL_GENERATION flag is on.

#ifndef YARP_THRIFT_GENERATOR_STRUCT_RETURN_GETIMPEDANCE_H
#define YARP_THRIFT_GENERATOR_STRUCT_RETURN_GETIMPEDANCE_H

#include <yarp/os/Wire.h>
#include <yarp/os/idl/WireTypes.h>
#include <yarp/dev/ReturnValue.h>

class return_getImpedance :
        public yarp::os::idl::WirePortable
{
public:
    // Fields
    yarp::dev::ReturnValue ret{};
    double stiffness{0.0};
    double damping{0.0};

    // Default constructor
    return_getImpedance() = default;

    // Constructor with field values
    return_getImpedance(const yarp::dev::ReturnValue& ret,
                        const double stiffness,
                        const double damping);

    // Read structure on a Wire
    bool read(yarp::os::idl::WireReader& reader) override;

    // Read structure on a Connection
    bool read(yarp::os::ConnectionReader& connection) override;

    // Write structure on a Wire
    bool write(const yarp::os::idl::WireWriter& writer) const override;

    // Write structure on a Connection
    bool write(yarp::os::ConnectionWriter& connection) const override;

    // Convert to a printable string
    std::string toString() const;

    // If you want to serialize this class without nesting, use this helper
    typedef yarp::os::idl::Unwrapped<return_getImpedance> unwrapped;

private:
    // read/write ret field
    bool read_ret(yarp::os::idl::WireReader& reader);
    bool write_ret(const yarp::os::idl::WireWriter& writer) const;
    bool nested_read_ret(yarp::os::idl::WireReader& reader);
    bool nested_write_ret(const yarp::os::idl::WireWriter& writer) const;

    // read/write stiffness field
    bool read_stiffness(yarp::os::idl::WireReader& reader);
    bool write_stiffness(const yarp::os::idl::WireWriter& writer) const;
    bool nested_read_stiffness(yarp::os::idl::WireReader& reader);
    bool nested_write_stiffness(const yarp::os::idl::WireWriter& writer) const;

    // read/write damping field
    bool read_damping(yarp::os::idl::WireReader& reader);
    bool write_damping(const yarp::os::idl::WireWriter& writer) const;
    bool nested_read_damping(yarp::os::idl::WireReader& reader);
    bool nested_write_damping(const yarp::os::idl::WireWriter& writer) const;
};

#endif // YARP_THRIFT_GENERATOR_STRUCT_RETURN_GETIMPEDANCE_H
