/*
 * SPDX-FileCopyrightText: 2006-2024 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef YARP_CONTROLBOARDCOUPLINGHANDLERLOGCOMPONENT_H
#define YARP_CONTROLBOARDCOUPLINGHANDLERLOGCOMPONENT_H

#include <yarp/os/LogComponent.h>

YARP_DECLARE_LOG_COMPONENT(CONTROLBOARDCOUPLINGHANDLER)

#endif // YARP_CONTROLBOARDCOUPLINGHANDLERLOGCOMPONENT_H
