/*
 * SPDX-FileCopyrightText: 2006-2021 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: BSD-3-Clause
 */

// Autogenerated by Thrift Compiler (0.14.1-yarped)
//
// This is an automatically generated file.
// It could get re-generated if the ALLOW_IDL_GENERATION flag is on.

#ifndef YARP_THRIFT_GENERATOR_STRUCT_COMMANDMESSAGEDATA_H
#define YARP_THRIFT_GENERATOR_STRUCT_COMMANDMESSAGEDATA_H

#include <yarp/dev/api.h>

#include <yarp/os/Wire.h>
#include <yarp/os/idl/WireTypes.h>
#include <yarp/os/Bottle.h>
#include <yarp/sig/Vector.h>

namespace yarp::dev {

class YARP_dev_API CommandMessageData :
        public yarp::os::idl::WirePortable
{
public:
    // Fields
    /**
     * header
     */
    yarp::os::Bottle head{};
    /**
     * body
     */
    yarp::sig::Vector body{};

    // Default constructor
    CommandMessageData() = default;

    // Constructor with field values
    CommandMessageData(const yarp::os::Bottle& head,
                       const yarp::sig::Vector& body);

    // Read structure on a Wire
    bool read(yarp::os::idl::WireReader& reader) override;

    // Read structure on a Connection
    bool read(yarp::os::ConnectionReader& connection) override;

    // Write structure on a Wire
    bool write(const yarp::os::idl::WireWriter& writer) const override;

    // Write structure on a Connection
    bool write(yarp::os::ConnectionWriter& connection) const override;

    // Convert to a printable string
    std::string toString() const;

    // If you want to serialize this class without nesting, use this helper
    typedef yarp::os::idl::Unwrapped<CommandMessageData> unwrapped;

private:
    // read/write head field
    bool read_head(yarp::os::idl::WireReader& reader);
    bool write_head(const yarp::os::idl::WireWriter& writer) const;
    bool nested_read_head(yarp::os::idl::WireReader& reader);
    bool nested_write_head(const yarp::os::idl::WireWriter& writer) const;

    // read/write body field
    bool read_body(yarp::os::idl::WireReader& reader);
    bool write_body(const yarp::os::idl::WireWriter& writer) const;
    bool nested_read_body(yarp::os::idl::WireReader& reader);
    bool nested_write_body(const yarp::os::idl::WireWriter& writer) const;
};

} // namespace yarp::dev

#endif // YARP_THRIFT_GENERATOR_STRUCT_COMMANDMESSAGEDATA_H
