/*
 * SPDX-FileCopyrightText: 2006-2021 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: BSD-3-Clause
 */

// Autogenerated by Thrift Compiler (0.14.1-yarped)
//
// This is an automatically generated file.
// It could get re-generated if the ALLOW_IDL_GENERATION flag is on.

#ifndef YARP_THRIFT_GENERATOR_STRUCT_SENSORMEASUREMENT_H
#define YARP_THRIFT_GENERATOR_STRUCT_SENSORMEASUREMENT_H

#include <yarp/dev/api.h>

#include <yarp/os/Wire.h>
#include <yarp/os/idl/WireTypes.h>
#include <yarp/sig/Vector.h>

namespace yarp::dev {

class YARP_dev_API SensorMeasurement :
        public yarp::os::idl::WirePortable
{
public:
    // Fields

    yarp::sig::Vector measurement{};
    double timestamp{0.0};

    // Default constructor
    SensorMeasurement() = default;

    // Constructor with field values
    SensorMeasurement(const yarp::sig::Vector& measurement,
                      const double timestamp);

    // Read structure on a Wire
    bool read(yarp::os::idl::WireReader& reader) override;

    // Read structure on a Connection
    bool read(yarp::os::ConnectionReader& connection) override;

    // Write structure on a Wire
    bool write(const yarp::os::idl::WireWriter& writer) const override;

    // Write structure on a Connection
    bool write(yarp::os::ConnectionWriter& connection) const override;

    // Convert to a printable string
    std::string toString() const;

    // If you want to serialize this class without nesting, use this helper
    typedef yarp::os::idl::Unwrapped<SensorMeasurement> unwrapped;

private:
    // read/write measurement field
    bool read_measurement(yarp::os::idl::WireReader& reader);
    bool write_measurement(const yarp::os::idl::WireWriter& writer) const;
    bool nested_read_measurement(yarp::os::idl::WireReader& reader);
    bool nested_write_measurement(const yarp::os::idl::WireWriter& writer) const;

    // read/write timestamp field
    bool read_timestamp(yarp::os::idl::WireReader& reader);
    bool write_timestamp(const yarp::os::idl::WireWriter& writer) const;
    bool nested_read_timestamp(yarp::os::idl::WireReader& reader);
    bool nested_write_timestamp(const yarp::os::idl::WireWriter& writer) const;
};

} // namespace yarp::dev

#endif // YARP_THRIFT_GENERATOR_STRUCT_SENSORMEASUREMENT_H
