/*
 * SPDX-FileCopyrightText: 2023-2023 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: LGPL-2.1-or-later
 */


// Generated by yarpDeviceParamParserGenerator (1.0)
// This is an automatically generated file. Please do not edit it.
// It will be re-generated if the cmake flag ALLOW_DEVICE_PARAM_PARSER_GERNERATION is ON.

// Generated on: Mon Jan 29 11:03:16 2024


#include "TestDeviceWGP_ParamsParser.h"
#include <yarp/os/LogStream.h>
#include <yarp/os/Value.h>

namespace {
    YARP_LOG_COMPONENT(TestDeviceWGPParamsCOMPONENT, "yarp.device.TestDeviceWGP")
}


std::vector<std::string> TestDeviceWGP_ParamsParser::getListOfParams() const
{
    std::vector<std::string> params;
    params.push_back("file_name");
    params.push_back("save_mode");
    params.push_back("add_marker");
    params.push_back("gggg::aaaaa");
    params.push_back("period");
    return params;
}


bool      TestDeviceWGP_ParamsParser::parseParams(const yarp::os::Searchable & config)
{
    //Check for --help option
    if (config.check("help"))
    {
        yCInfo(TestDeviceWGPParamsCOMPONENT) << getDocumentationOfDeviceParams();
    }

    std::string config_string = config.toString();
    yarp::os::Property prop_check(config_string.c_str());
    //Parser of parameter file_name
    {
        if (config.check("file_name"))
        {
            m_file_name = config.find("file_name").asString();
            yCInfo(TestDeviceWGPParamsCOMPONENT) << "Parameter 'file_name' using value:" << m_file_name;
        }
        else
        {
            yCError(TestDeviceWGPParamsCOMPONENT) << "Mandatory parameter 'file_name' not found!";
            yCError(TestDeviceWGPParamsCOMPONENT) << "Description of the parameter: The name of the file written by the module";
            return false;
        }
        prop_check.unput("file_name");
    }

    //Parser of parameter save_mode
    {
        if (config.check("save_mode"))
        {
            m_save_mode = config.find("save_mode").asString();
            yCInfo(TestDeviceWGPParamsCOMPONENT) << "Parameter 'save_mode' using value:" << m_save_mode;
        }
        else
        {
            yCInfo(TestDeviceWGPParamsCOMPONENT) << "Parameter 'save_mode' using DEFAULT value:" << m_save_mode;
        }
        prop_check.unput("save_mode");
    }

    //Parser of parameter add_marker
    {
        if (config.check("add_marker"))
        {
            m_add_marker = config.find("add_marker").asBool();
            yCInfo(TestDeviceWGPParamsCOMPONENT) << "Parameter 'add_marker' using value:" << m_add_marker;
        }
        else
        {
            yCInfo(TestDeviceWGPParamsCOMPONENT) << "Parameter 'add_marker' using DEFAULT value:" << m_add_marker;
        }
        prop_check.unput("add_marker");
    }

    //Parser of parameter gggg::aaaaa
    {
        yarp::os::Bottle sectionp;
        sectionp = config.findGroup("gggg");
        if (sectionp.check("aaaaa"))
        {
            m_gggg_aaaaa = sectionp.find("aaaaa").asBool();
            yCInfo(TestDeviceWGPParamsCOMPONENT) << "Parameter 'gggg::aaaaa' using value:" << m_gggg_aaaaa;
        }
        else
        {
            yCInfo(TestDeviceWGPParamsCOMPONENT) << "Parameter 'gggg::aaaaa' using DEFAULT value:" << m_gggg_aaaaa;
        }
        prop_check.unput("gggg::aaaaa");
    }

    //Parser of parameter period
    {
        if (config.check("period"))
        {
            m_period = config.find("period").asFloat64();
            yCInfo(TestDeviceWGPParamsCOMPONENT) << "Parameter 'period' using value:" << m_period;
        }
        else
        {
            yCError(TestDeviceWGPParamsCOMPONENT) << "Mandatory parameter 'period' not found!";
            yCError(TestDeviceWGPParamsCOMPONENT) << "Description of the parameter: If set, it will add a marker at the beginning and at the ending of each received waveform.";
            yCError(TestDeviceWGPParamsCOMPONENT) << "Remember: Units for this parameter are: 's'";
            return false;
        }
        prop_check.unput("period");
    }

    /*
    //This code check if the user set some parameter which are not check by the parser
    //If the parser is set in strict mode, this will generate an error
    if (prop_check.size() > 0)
    {
        bool extra_params_found = false;
        for (auto it=prop_check.begin(); it!=prop_check.end(); it++)
        {
            if (m_parser_is_strict)
            {
                yCError(TestDeviceWGPParamsCOMPONENT) << "User asking for parameter: "<<it->name <<" which is unknown to this parser!";
                extra_params_found = true;
            }
            else
            {
                yCWarning(TestDeviceWGPParamsCOMPONENT) << "User asking for parameter: "<< it->name <<" which is unknown to this parser!";
            }
        }

       if (m_parser_is_strict && extra_params_found)
       {
           return false;
       }
    }
    */
    return true;
}


std::string      TestDeviceWGP_ParamsParser::getDocumentationOfDeviceParams() const
{
    std::string doc;
    doc = doc + std::string("\n=============================================\n");
    doc = doc + std::string("This is the help for device: TestDeviceWGP\n");
    doc = doc + std::string("\n");
    doc = doc + std::string("This is the list of the parameters accepted by the device:\n");
    doc = doc + std::string("'file_name': The name of the file written by the module\n");
    doc = doc + std::string("'save_mode': Affects the behavior of the module and defines the save mode, as described in the documentation.\n");
    doc = doc + std::string("'add_marker': If set, it will add a marker at the beginning and at the ending of each received waveform.\n");
    doc = doc + std::string("'gggg::aaaaa': If set, it will add a marker at the beginning and at the ending of each received waveform.\n");
    doc = doc + std::string("'period': If set, it will add a marker at the beginning and at the ending of each received waveform.\n");
    doc = doc + std::string("\n");
    doc = doc + std::string("Here are some examples of invocation command with yarpdev, with all params:\n");
    doc = doc + " yarpdev --device TestDeviceWGP --file_name audio_out.wav --save_mode overwrite_file --add_marker <optional_value> --gggg::aaaaa <optional_value> --period <mandatory_value>\n";
    doc = doc + std::string("Using only mandatory params:\n");
    doc = doc + " yarpdev --device TestDeviceWGP --file_name audio_out.wav --period <mandatory_value>\n";
    doc = doc + std::string("=============================================\n");    return doc;
}
