### STRING UTILITIES

MACRO(CAR var)
  SET(${var} ${ARGV1})
ENDMACRO(CAR)

MACRO(CDR var junk)
  SET(${var} ${ARGN})
ENDMACRO(CDR)

MACRO(LIST_LENGTH var)
  SET(entries)
  FOREACH(e ${ARGN})
    SET(entries "${entries}.")
  ENDFOREACH(e)
  STRING(LENGTH ${entries} ${var})
ENDMACRO(LIST_LENGTH)

MACRO(LIST_INDEX var index)
  SET(list . ${ARGN})
  FOREACH(i RANGE 1 ${index})
    CDR(list ${list})
  ENDFOREACH(i)
  CAR(${var} ${list})
ENDMACRO(LIST_INDEX)

MACRO(LIST_CONTAINS var value)
  SET(${var})
  FOREACH (value2 ${ARGN})
    IF (${value} STREQUAL ${value2})
      SET(${var} TRUE)
    ENDIF (${value} STREQUAL ${value2})
  ENDFOREACH (value2)
ENDMACRO(LIST_CONTAINS)

##### specific
MACRO(DD_FIND_LOCAL_LIB var dd LIBS)
 FOREACH(lib ${LIBS})
        SET(LOCAL_PATH ${CMAKE_SOURCE_DIR}/src/libYARP_dev/src/${dd}/${OS_TAG}/dd_orig/lib)
        FILE(GLOB TEMP ${LOCAL_PATH}/${lib})
	IF (TEMP)
	   MESSAGE(STATUS "OK Found: ${LOCAL_PATH}/${lib}")
	   SET(PATH-${DD} ${LOCAL_PATH}/${lib} CACHE FILEPATH "Lib required by ${DD}")
	ELSE(TEMP)
	   MESSAGE(ERROR "NOT found: ${LOCAL_PATH}/${lib}")
	   SET(PATH-${DD} "NOT-FOUND: ${lib}" CACHE FILEPATH "Lib required by ${DD}")
	ENDIF(TEMP)
 ENDFOREACH(lib ${ARGN})
ENDMACRO(DD_FIND_LOCAL_LIB)

MACRO(DD_FIND_EXTERNAL_LIB var dd LIBS)
   MESSAGE(STATUS "${dd} requires proper installation of: ${LIBS}")
   MESSAGE(STATUS "For now YARP2 is going to assume you took care of that")
ENDMACRO(DD_FIND_EXTERNAL_LIB)