/*
 * SPDX-FileCopyrightText: 2006-2021 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef YARP_REMOTECONTROLBOARDLOGCOMPONENT_H
#define YARP_REMOTECONTROLBOARDLOGCOMPONENT_H

#include <yarp/os/LogComponent.h>

YARP_DECLARE_LOG_COMPONENT(REMOTECONTROLBOARD)

#endif // YARP_REMOTECONTROLBOARDLOGCOMPONENT_H
