# SPDX-FileCopyrightText: 2006-2021 Istituto Italiano di Tecnologia (IIT)
# SPDX-License-Identifier: BSD-3-Clause

set(YARP_COMPILE_BINDINGS ON CACHE BOOL "")
set(CREATE_LUA ON CACHE BOOL "")
set(CREATE_RUBY ON CACHE BOOL "")
set(CREATE_PYTHON ON CACHE BOOL "")
set(CREATE_TCL ON CACHE BOOL "")
set(CREATE_JAVA ON CACHE BOOL "")
set(CREATE_CSHARP ON CACHE BOOL "")
set(CREATE_PERL ON CACHE BOOL "")
set(CREATE_OCTAVE ON CACHE BOOL "")
