
IF(PKGCONFIG_EXECUTABLE)
	PKGCONFIG("gtk+-2.0" GTKPLUS_INCLUDE_DIR_GUESS GTKPLUS_LIBRARY_DIR_GUESS GTKPLUS_LINK_FLAGS GTKPLUS_C_FLAGS)
ENDIF(PKGCONFIG_EXECUTABLE)

SET(GTKPLUS_LINK_FLAGS "${GTKPLUS_LINK_FLAGS}" CACHE INTERNAL "gtk+ link flags")
SET(GTKPLUS_C_FLAGS "${GTKPLUS_C_FLAGS}" CACHE INTERNAL "gtk+ include flags")

#ADD_DEFINITIONS(${GTKPLUS_C_FLAGS})
#LINK_LIBRARIES(${GTKPLUS_LINK_FLAGS})

IF (GTKPLUS_C_FLAGS)
	SET(GtkPlus_FOUND TRUE)
ELSE (GTKPLUS_C_FLAGS)
	SET(GtkPlus_FOUND FALSE)
ENDIF (GTKPLUS_C_FLAGS)

