IF(UNIX)
 IF(NOT PKGCONFIG_EXECUTABLE) 
   INCLUDE(UsePkgConfig)
 ENDIF(NOT PKGCONFIG_EXECUTABLE)
 IF(PKGCONFIG_EXECUTABLE)
   PKGCONFIG("gthread-2.0" GTHREAD_INCLUDE_DIR GTHREAD_LIBRARY_DIR GTHREAD_LINK_FLAGS GTHREAD_C_FLAGS)
 ENDIF(PKGCONFIG_EXECUTABLE)

 SET(GTHREAD_LINK_FLAGS "${GTHREAD_LINK_FLAGS}" CACHE INTERNAL "gthread link flags")
 SET(GTHREAD_C_FLAGS "${GTHREAD_C_FLAGS}" CACHE INTERNAL "gthread include flags")
 SET(GTHREAD_INCLUDE_DIR "${GTHREAD_INCLUDE_DIR}" CACHE INTERNAL "gthread include directory")

 IF (GTHREAD_C_FLAGS)
 	SET(Gthread_FOUND TRUE)
 ELSE (GTHREAD_C_FLAGS)
	SET(Gthread_FOUND FALSE)
 ENDIF (GTHREAD_C_FLAGS)
ELSE (UNIX)
  FIND_LIBRARY(GTK_thread_lib
	NAMES gthread-2.0
	PATHS $ENV{GTK_BASEPATH}/lib)
  IF (GTK_thread_lib)
    SET(Gthread_FOUND TRUE)
    SET(GTHREAD_LINK_FLAGS
	  ${GTK_thread_lib})
  ENDIF(GTK_thread_lib)
ENDIF (UNIX)


