
FIND_PATH(ACE_INCLUDE_DIR ace/ACE.h /usr/include /usr/local/include $ENV{ACE_ROOT} DOC "directory containing ace/*.h for ACE library")

# this is for easy YARP1 compatability, not too important
SET(OS_TAG linux)
IF (WIN32)
	SET(OS_TAG winnt)
ENDIF (WIN32)
SET(YARP_ACE_CONFIG_GUESS $ENV{ACE_ROOT}/../../include/${OS_TAG})

#FIND_PATH(ACE_INCLUDE_CONFIG_DIR ace/config.h /usr/include /usr/local/include $ENV{ACE_ROOT} ${YARP_ACE_CONFIG_GUESS} DOC "directory containing ace/config.h")
SET(ACE_INCLUDE_CONFIG_DIR ${ACE_INCLUDE_DIR})

FIND_LIBRARY(ACE_LIBRARY NAMES ACE ace PATHS /usr/lib /usr/local/lib $ENV{ACE_ROOT}/lib $ENV{ACE_ROOT} DOC "ACE library file")

IF (WIN32 AND NOT CYGWIN)
	SET(CMAKE_DEBUG_POSTFIX "d")
	FIND_LIBRARY(ACE_DEBUG_LIBRARY NAMES ACE${CMAKE_DEBUG_POSTFIX} ace${CMAKE_DEBUG_POSTFIX} PATHS /usr/lib /usr/local/lib $ENV{ACE_ROOT}/lib $ENV{ACE_ROOT} DOC "ACE library file (debug version)")
ENDIF (WIN32 AND NOT CYGWIN)

#FIND_LIBRARY(ACE_DEBUG_LIBRARY NAMES ACED ACEd aced PATHS /usr/lib /usr/local/lib $ENV{ACE_ROOT}/lib $ENV{ACE_ROOT})

IF (ACE_INCLUDE_DIR AND ACE_LIBRARY AND ACE_INCLUDE_CONFIG_DIR)
	SET(ACE_FOUND TRUE)
ELSE (ACE_INCLUDE_DIR AND ACE_LIBRARY AND ACE_INCLUDE_CONFIG_DIR)
	SET(ACE_FOUND FALSE)
ENDIF (ACE_INCLUDE_DIR AND ACE_LIBRARY AND ACE_INCLUDE_CONFIG_DIR)

IF (ACE_DEBUG_LIBRARY)
	SET(ACE_DEBUG_FOUND TRUE)
ENDIF (ACE_DEBUG_LIBRARY)

IF (ACE_FOUND)
	IF (NOT Ace_FIND_QUIETLY)
		MESSAGE(STATUS "Found ACE library: ${ACE_LIBRARY}")
		MESSAGE(STATUS "Found ACE include: ${ACE_INCLUDE_DIR}")
	ENDIF (NOT Ace_FIND_QUIETLY)
ELSE (ACE_FOUND)
	IF (Ace_FIND_REQUIRED)
		MESSAGE(FATAL_ERROR "Could not find ACE")
	ENDIF (Ace_FIND_REQUIRED)
ENDIF (ACE_FOUND)
