# Creates:
# GTKMM_INCLUDE_DIR   - Directories to include to use GTKMM
# GTKMM_LINK_FLAGS    - Files to link against to use GTKMM
# GTKMM_LINK_BASE     - Files to link from C libs
# GtkMM_FOUND         - If false, don't try to use GTKMM

# gtkmm and libglademm seem to be coupled in FindGtkMMWin32.cmake
# so mirror that behavior here

IF(PKGCONFIG_EXECUTABLE)
  PKGCONFIG(gtkmm-2.4 GTKMM_INCLUDE_DIR GTKMM_LINK_FLAGS
            GTKMM_LINK_BASE GTKMM_C_FLAGS)
  PKGCONFIG(libglademm-2.4 GLADE_INCLUDE_DIR GLADE_LINK_FLAGS
            GLADE_LINK_BASE GLADE_C_FLAGS)
ENDIF(PKGCONFIG_EXECUTABLE)

IF (GLADE_LINK_BASE)
  MESSAGE(STATUS " pkg-config found glade")
  IF (GTKMM_LINK_BASE)
    SET(GTKMM_INCLUDE_DIR ${GTKMM_INCLUDE_DIR} ${GLADE_INCLUDE_DIR})
    SET(GTKMM_LINK_FLAGS ${GTKMM_LINK_FLAGS} ${GLADE_LINK_FLAGS})
    SET(GTKMM_LINK_BASE ${GTKMM_LINK_BASE} ${GLADE_LINK_BASE})
    SET(GTKMM_C_FLAGS ${GTKMM_C_FLAGS} ${GLADE_C_FLAGS})
  ENDIF (GTKMM_LINK_BASE)
ELSE (GLADE_LINK_BASE)
  MESSAGE(WARNING " pkg-config could not find glade")
ENDIF (GLADE_LINK_BASE)

IF (GTKMM_LINK_BASE)
  MESSAGE(STATUS " pkg-config found gtkmm")
  SET(GtkMM_FOUND TRUE)
ELSE (GTKMM_LINK_BASE)
  MESSAGE(ERROR " pkg-config could not find gtkmm")
  SET(GtkMM_FOUND FALSE)
ENDIF (GTKMM_LINK_BASE)


IF (GtkMM_FOUND)
  MESSAGE(STATUS GTKMM_INCLUDE_DIR ${GTKMM_INCLUDE_DIR})
  MESSAGE(STATUS GTKMM_LINK_BASE ${GTKMM_LINK_BASE})
  MESSAGE(STATUS GTKMM_LINK_FLAGS ${GTKMM_LINK_FLAGS})
  MESSAGE(STATUS GTKMM_C_FLAGS ${GTKMM_C_FLAGS})
ENDIF (GtkMM_FOUND)

