
IF(PKGCONFIG_EXECUTABLE)
	PKGCONFIG(portaudio-2.0 PORTNAME_INCLUDE_DIR PORTAUDIO_LINK_DIRECTORIES
			        PORTAUDIO_LIBRARIES PORTAUDIO_CFLAGS)
ENDIF(PKGCONFIG_EXECUTABLE)


#message(STATUS "inc: -${PORTAUDIO_INCLUDE_DIR}")
#message(STATUS "link flags: -${PORTAUDIO_LINK_FLAGS}")
#message(STATUS "cflags: -${PORTAUDIO_CFLAGS}")
#message(STATUS "link dir: -${PORTAUDIO_LINK_DIR}")

IF (PORT_AUDIO_CFLAGS)
	SET(PortAudio_FOUND TRUE)
ELSE (PORT_AUDIO_CFLAGS)
	SET(PortAudio_FOUND FALSE)
ENDIF (PORT_AUDIO_CFLAGS)
