
SET(COEXIST_WITH_YARP1 FALSE CACHE BOOL "Do you want to work with YARP1, an older version of YARP")

IF (COEXIST_WITH_YARP1)

	FIND_PATH(YARP1_INCLUDE_DIR yarp/YARPPort.h /usr/include /usr/local/include $ENV{YARP_ROOT}/include DOC "directory containing yarp/*.h for YARP1, an older version of YARP")


	IF (YARP1_INCLUDE_DIR)
		SET(YARP1_FOUND TRUE)
	ELSE (YARP1_INCLUDE_DIR)
		SET(YARP1_FOUND FALSE)
	ENDIF (YARP1_INCLUDE_DIR)

	IF (YARP1_FOUND)
		IF (NOT Yarp1_FIND_QUIETLY)
			MESSAGE(STATUS "Found YARP1 include: ${YARP1_INCLUDE_DIR}")
		ENDIF (NOT Yarp1_FIND_QUIETLY)
	ELSE (YARP1_FOUND)
		IF (NOT Yarp1_FIND_QUIETLY)
			MESSAGE(STATUS "No old YARP1 header files found")
		ENDIF (NOT Yarp1_FIND_QUIETLY)
	ENDIF (YARP1_FOUND)

ELSE (COEXIST_WITH_YARP1)

	SET(YARP1_FOUND FALSE)

ENDIF (COEXIST_WITH_YARP1)

