
IF (ACE_DEBUG_FOUND)
 LINK_LIBRARIES(optimized ${ACE_LIBRARY} debug ${ACE_DEBUG_LIBRARY})
ELSE (ACE_DEBUG_FOUND)
 LINK_LIBRARIES(${ACE_LIBRARY})
ENDIF (ACE_DEBUG_FOUND)

IF (WIN32 AND NOT CYGWIN)
  LINK_LIBRARIES(winmm)
ENDIF (WIN32 AND NOT CYGWIN)

