/*
 * SPDX-FileCopyrightText: 2006-2021 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef YARP_CONTROLBOARDREMAPPERLOGCOMPONENT_H
#define YARP_CONTROLBOARDREMAPPERLOGCOMPONENT_H

#include <yarp/os/LogComponent.h>

YARP_DECLARE_LOG_COMPONENT(CONTROLBOARDREMAPPER)

#endif // YARP_CONTROLBOARDREMAPPERLOGCOMPONENT_H
