/*
 * SPDX-FileCopyrightText: 2006-2021 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: BSD-3-Clause
 */

// Autogenerated by Thrift Compiler (0.14.1-yarped)
//
// This is an automatically generated file.
// It could get re-generated if the ALLOW_IDL_GENERATION flag is on.

#ifndef YARP_THRIFT_GENERATOR_STRUCT_RETURN_GETALLTRANSFORMS_H
#define YARP_THRIFT_GENERATOR_STRUCT_RETURN_GETALLTRANSFORMS_H

#include <yarp/os/Wire.h>
#include <yarp/os/idl/WireTypes.h>
#include <yarp/math/FrameTransform.h>

class return_getAllTransforms :
        public yarp::os::idl::WirePortable
{
public:
    // Fields
    bool retvalue;
    std::vector<yarp::math::FrameTransform> transforms_list;

    // Default constructor
    return_getAllTransforms();

    // Constructor with field values
    return_getAllTransforms(const bool retvalue,
                            const std::vector<yarp::math::FrameTransform>& transforms_list);

    // Read structure on a Wire
    bool read(yarp::os::idl::WireReader& reader) override;

    // Read structure on a Connection
    bool read(yarp::os::ConnectionReader& connection) override;

    // Write structure on a Wire
    bool write(const yarp::os::idl::WireWriter& writer) const override;

    // Write structure on a Connection
    bool write(yarp::os::ConnectionWriter& connection) const override;

    // Convert to a printable string
    std::string toString() const;

    // If you want to serialize this class without nesting, use this helper
    typedef yarp::os::idl::Unwrapped<return_getAllTransforms> unwrapped;

    class Editor :
            public yarp::os::Wire,
            public yarp::os::PortWriter
    {
    public:
        // Editor: default constructor
        Editor();

        // Editor: constructor with base class
        Editor(return_getAllTransforms& obj);

        // Editor: destructor
        ~Editor() override;

        // Editor: Deleted constructors and operator=
        Editor(const Editor& rhs) = delete;
        Editor(Editor&& rhs) = delete;
        Editor& operator=(const Editor& rhs) = delete;
        Editor& operator=(Editor&& rhs) = delete;

        // Editor: edit
        bool edit(return_getAllTransforms& obj, bool dirty = true);

        // Editor: validity check
        bool isValid() const;

        // Editor: state
        return_getAllTransforms& state();

        // Editor: start editing
        void start_editing();

#ifndef YARP_NO_DEPRECATED // Since YARP 3.2
        YARP_DEPRECATED_MSG("Use start_editing() instead")
        void begin()
        {
            start_editing();
        }
#endif // YARP_NO_DEPRECATED

        // Editor: stop editing
        void stop_editing();

#ifndef YARP_NO_DEPRECATED // Since YARP 3.2
        YARP_DEPRECATED_MSG("Use stop_editing() instead")
        void end()
        {
            stop_editing();
        }
#endif // YARP_NO_DEPRECATED

        // Editor: retvalue field
        void set_retvalue(const bool retvalue);
        bool get_retvalue() const;
        virtual bool will_set_retvalue();
        virtual bool did_set_retvalue();

        // Editor: transforms_list field
        void set_transforms_list(const std::vector<yarp::math::FrameTransform>& transforms_list);
        void set_transforms_list(size_t index, const yarp::math::FrameTransform& elem);
        const std::vector<yarp::math::FrameTransform>& get_transforms_list() const;
        virtual bool will_set_transforms_list();
        virtual bool did_set_transforms_list();

        // Editor: clean
        void clean();

        // Editor: read
        bool read(yarp::os::ConnectionReader& connection) override;

        // Editor: write
        bool write(yarp::os::ConnectionWriter& connection) const override;

    private:
        // Editor: state
        return_getAllTransforms* obj;
        bool obj_owned;
        int group;

        // Editor: dirty variables
        bool is_dirty;
        bool is_dirty_retvalue;
        bool is_dirty_transforms_list;
        int dirty_count;

        // Editor: send if possible
        void communicate();

        // Editor: mark dirty overall
        void mark_dirty();

        // Editor: mark dirty single fields
        void mark_dirty_retvalue();
        void mark_dirty_transforms_list();

        // Editor: dirty_flags
        void dirty_flags(bool flag);
    };

private:
    // read/write retvalue field
    bool read_retvalue(yarp::os::idl::WireReader& reader);
    bool write_retvalue(const yarp::os::idl::WireWriter& writer) const;
    bool nested_read_retvalue(yarp::os::idl::WireReader& reader);
    bool nested_write_retvalue(const yarp::os::idl::WireWriter& writer) const;

    // read/write transforms_list field
    bool read_transforms_list(yarp::os::idl::WireReader& reader);
    bool write_transforms_list(const yarp::os::idl::WireWriter& writer) const;
    bool nested_read_transforms_list(yarp::os::idl::WireReader& reader);
    bool nested_write_transforms_list(const yarp::os::idl::WireWriter& writer) const;
};

#endif // YARP_THRIFT_GENERATOR_STRUCT_RETURN_GETALLTRANSFORMS_H
