/*
 * SPDX-FileCopyrightText: 2006-2021 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: BSD-3-Clause
 */

// Autogenerated by Thrift Compiler (0.14.1-yarped)
//
// This is an automatically generated file.
// It could get re-generated if the ALLOW_IDL_GENERATION flag is on.

#ifndef YARP_THRIFT_GENERATOR_SERVICE_TESTMULTIPLECONTAINERS_H
#define YARP_THRIFT_GENERATOR_SERVICE_TESTMULTIPLECONTAINERS_H

#include <yarp/os/Wire.h>
#include <yarp/os/idl/WireTypes.h>
#include <yarp/os/ApplicationNetworkProtocolVersion.h>

class TestMultipleContainers :
        public yarp::os::Wire
{
public:
    //ProtocolVersion
    virtual yarp::os::ApplicationNetworkProtocolVersion getLocalProtocolVersion();
    virtual yarp::os::ApplicationNetworkProtocolVersion getRemoteProtocolVersion();
    virtual bool checkProtocolVersion();

    // Constructor
    TestMultipleContainers();

    //Service methods
    virtual bool testList1(const std::vector<std::int32_t>& a);

    virtual bool testList2(const std::vector<std::int32_t>& a, const std::vector<std::int32_t>& b);

    virtual bool testMap1(const std::map<std::int32_t, std::string>& a);

    virtual bool testMap2(const std::map<std::int32_t, std::string>& a, const std::map<std::int32_t, std::string>& b);

    virtual bool testSet1(const std::set<std::int32_t>& a);

    virtual bool testSet2(const std::set<std::int32_t>& a, const std::set<std::int32_t>& b);

    // help method
    virtual std::vector<std::string> help(const std::string& functionName = "--all");

    // read from ConnectionReader
    bool read(yarp::os::ConnectionReader& connection) override;
};

#endif // YARP_THRIFT_GENERATOR_SERVICE_TESTMULTIPLECONTAINERS_H
