/*
 * SPDX-FileCopyrightText: 2006-2021 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: BSD-3-Clause
 */

// Autogenerated by Thrift Compiler (0.14.1-yarped)
//
// This is an automatically generated file.
// It could get re-generated if the ALLOW_IDL_GENERATION flag is on.

#ifndef YARP_THRIFT_GENERATOR_STRUCT_IRGBDMSGS_RETURN_GETLASTERRORMSG_H
#define YARP_THRIFT_GENERATOR_STRUCT_IRGBDMSGS_RETURN_GETLASTERRORMSG_H

#include <yarp/os/Wire.h>
#include <yarp/os/idl/WireTypes.h>
#include <yarp/dev/ReturnValue.h>
#include <yarp/os/Stamp.h>

class IRGBDMsgs_return_getLastErrorMsg :
        public yarp::os::idl::WirePortable
{
public:
    // Fields
    yarp::dev::ReturnValue ret{};
    std::string errorMsg{};
    yarp::os::Stamp stamp{};

    // Default constructor
    IRGBDMsgs_return_getLastErrorMsg() = default;

    // Constructor with field values
    IRGBDMsgs_return_getLastErrorMsg(const yarp::dev::ReturnValue& ret,
                                     const std::string& errorMsg,
                                     const yarp::os::Stamp& stamp);

    // Read structure on a Wire
    bool read(yarp::os::idl::WireReader& reader) override;

    // Read structure on a Connection
    bool read(yarp::os::ConnectionReader& connection) override;

    // Write structure on a Wire
    bool write(const yarp::os::idl::WireWriter& writer) const override;

    // Write structure on a Connection
    bool write(yarp::os::ConnectionWriter& connection) const override;

    // Convert to a printable string
    std::string toString() const;

    // If you want to serialize this class without nesting, use this helper
    typedef yarp::os::idl::Unwrapped<IRGBDMsgs_return_getLastErrorMsg> unwrapped;

private:
    // read/write ret field
    bool read_ret(yarp::os::idl::WireReader& reader);
    bool write_ret(const yarp::os::idl::WireWriter& writer) const;
    bool nested_read_ret(yarp::os::idl::WireReader& reader);
    bool nested_write_ret(const yarp::os::idl::WireWriter& writer) const;

    // read/write errorMsg field
    bool read_errorMsg(yarp::os::idl::WireReader& reader);
    bool write_errorMsg(const yarp::os::idl::WireWriter& writer) const;
    bool nested_read_errorMsg(yarp::os::idl::WireReader& reader);
    bool nested_write_errorMsg(const yarp::os::idl::WireWriter& writer) const;

    // read/write stamp field
    bool read_stamp(yarp::os::idl::WireReader& reader);
    bool write_stamp(const yarp::os::idl::WireWriter& writer) const;
    bool nested_read_stamp(yarp::os::idl::WireReader& reader);
    bool nested_write_stamp(const yarp::os::idl::WireWriter& writer) const;
};

#endif // YARP_THRIFT_GENERATOR_STRUCT_IRGBDMSGS_RETURN_GETLASTERRORMSG_H
