### parameters are 
# $1: hostname
# $1: os type (winxp, lenny, etch, karmic ...)

CMAKE_OPTIONS="-DCREATE_GUIS:BOOL=TRUE -DCREATE_LIB_MATH:BOOL=TRUE -DENABLE_DASHBOARD_SUBMIT:BOOL=TRUE -DUSE_PORT_AUTHENTICATION:BOOL=TRUE"

