#!/usr/bin/perl

# Copyright: (C) 2010 RobotCub Consortium
# Author: Paul Fitzpatrick
# CopyPolicy: Released under the terms of the LGPLv2.1 or later, see LGPL.TXT

# Sort a list of names, used by "who_wrote"

use Lingua::EN::NameParse;

sub by_last_name {
  my $nom = Lingua::EN::NameParse->new(auto_clean  => 1);
  my @names;
  for my $name ($a, $b) {
    my $err;
    chomp($name);
    if ($nom->parse($name)){
      warn "Cannot deal with $name";
    }
    my %result = $nom->components;
    push(@names,\%result);
  }
  return lc $names[0]->{surname_1} cmp lc $names[1]->{surname_1};
}

my @noms = <STDIN>;
for my $line (sort by_last_name @noms){
  chomp($line);
  print $line, "\n";
}

