#!/usr/bin/perl -w

# Copyright: (C) 2010 RobotCub Consortium
# Author: Paul Fitzpatrick
# CopyPolicy: Released under the terms of the LGPLv2.1 or later, see LGPL.TXT

my $fname = $ARGV[0];


my $std_license = "
/*
 * Copyright (C) 2006 Author McAuthor
 * CopyPolicy: Released under the terms of the GNU GPL v2.0.
 *
 */
";


print "$fname\n";

my $txt = "";
open(FIN,"<license_check/$fname");
while (<FIN>) {
    $txt .= $_;
}
close(FIN);

$txt =~ s/Department of Robotics Brain and Cognitive Sciences - Istituto Italiano di Tecnologia/IITRBCS/;
$txt =~ s/Robotics, Brain and Cognitive Sciences - Italian Institute of Technology .IIT./IITRBCS/;
$txt =~ s/Robotics Brain and Cognitive Sciences, Istituto Italiano di Tecnologia/IITRBCS/;
$txt =~ s/Robotics Brain and Cognitive Sciences Department, Istituto Italiano di Tecnologia/IITRBCS/;

$txt =~ s/iCub Facility, Istituto Italiano di Tecnologia/IITICUB/;
$txt =~ s/iCub Facility - Istituto Italiano di Tecnologia/IITICUB/;
$txt =~ s/iCub Facility/IITICUB/;

$txt =~ s/Copy Policy/CopyPolicy/;

$txt =~ s/Original code by Lee Thomason.*/Copyright: Lee Thomason/;

$txt =~ s/The RobotCub Consortium\.?/RobotCub Consortium/ig;
$txt =~ s/Robotcub Consortium\.?/RobotCub Consortium/ig;

$txt =~ s/-->//;


if (!($txt =~ /Thomason/)) {
    $txt =~ s|www.sourceforge.net/projects/tinyxml|Copyright: Lee Thomason|;
}

my $report = "skipped";

my $policy = "unknown";
my $copyright = "unknown";
my $authors = "";

my $quiet = 1;
if ($txt=~/license/i || $txt=~/copyright/i || $txt=~/rights/i) {
    $quiet = 0;
}


if ($copyright eq "unknown") {
    if ($txt=~/copyright\:\s*([^\"\'\*\r\n]+)\s*[\n\r\*]/i) {
        $copyright = $1;
    } elsif ($txt =~ /copyright\:?\s*([^\(0-9][^\"\'\*\r\n]+)\s*[\n\r\*]/i) {
        $copyright = $1;
    }
}

if ($txt=~/CopyPolicy\:\s*(.*)/i) {
    $policy = $1;
}

if ($txt=~/GNU Lesser General Public license/) {
    if ($txt=~/we personally strongly object/) {
        $policy = "LGPL; non-binding note discouraging certain uses";
    }
}

if ($policy eq "unknown") {
    if ($txt =~ /GNU Lesser General Public License/) {
        if ($txt =~ /either version 2.1/) {
            $policy = "LGPLv2.1 or later";
        }
    }
}

if ($policy eq "unknown") {
    if ($txt =~ /GNU General Public License/) {
        if ($txt =~ /version 2 or/) {
            $policy = "GPLv2 or later";
        }
    }
}

if ($policy eq "unknown") {
    if ($txt =~ /GNU Library General Public/) {
        if ($txt =~ /version 2 of the License. or/) {
            $policy = "LGPLv2 or later";
        }
    }
}

if ($policy eq "unknown") {
    if ($txt =~ /GNU Lesser General Public/) {
        if ($txt =~ /version 2 of the License. or/) {
            $policy = "LGPLv2 or later";
        }
    }
}

if ($policy eq "unknown") {
    if ($txt =~ / rbock . /) {
        # tinyxml has blanket LGPLv2.1 license; tolerate this for now
        $copyright = "(C) 1998 - 2008  Dr. Roland Bock";
        $policy = "LGPLv2.1 or later";
    }
}

if ($policy eq "unknown") {
    if ($txt =~ /Distributed under the OSI-approved BSD License/) {
        $policy = "3-clause BSD";
    }
}

if ($txt =~ /(The author disclaims copyright to this source code)/) {
    $copyright = $1;
}

if ($txt =~ /here is a blessing/) {
    $policy = "In place of a legal notice, a blessing is given."
}

if ($policy =~ /unknown/) {
    if ($txt =~ /Permission is granted to anyone to use this software for any/) {
        if ($txt =~ /This notice may not be removed or altered from any source/) {
            $policy = "zlib";
        } else {
            if ($txt =~ /All advertising materials mentioning features or use of this software/) {
                $policy = "4-clause BSD";
            } else {
                $policy = "3-clause BSD";
            }
        }
    }
    if ($txt =~ /Everyone is permitted to copy and distribute verbatim copies/) {
        $policy = "copying and distributing verbatim copies allowed";
    }
}

if ($txt =~ /Bayer pattern decoding functions/) {
    $copyright = "Damien Douxchamps and Frederic Devernay";
    $policy = "LGPLv2.1";
}

if ($txt =~ /Licensed to the Apache Software Foundation/) {
    $copyright = "Apache Software Foundation";
    $policy = "Apache License, Version 2.0";
}

if ($txt =~ /Licensed under the Apache License/) {
    $policy = "Apache License, Version 2.0";
}

if ($txt =~ /Alexander Chemeris/) {
    $policy = "3-clause BSD";
}

if ($copyright eq "unknown") {
    if ($txt =~ /Lee Thomason/) {
        $copyright = "Lee Thomason";
        $policy = "zlib";
    }
}

if ($copyright =~ /RobotCub/i || $copyright =~ /IITRBCS/i || $copyright =~ /IITICUB/i) {
    if ($txt =~ /authors?: *([^ \n\r].*[^ \n\r])/i) {
        $authors = $1;
        $authors =~ s/[^ \n\r]*\@[^ \n\r]*//g;
    }
}

if ($policy eq "unknown") {
    if ($fname =~ /sfun_time.c/) {
        $copyright = "2009 The MathWorks, Inc.";
        $policy = "3-clause BSD";
    }
}

if ($policy eq "unknown") {
    if ($fname =~ /extern\/goocanvas\/goocanvas/) {
        $copyright = "2005-2008 Damon Chaplin";
        $policy = "LGPLv2";
    }
}

if ($policy eq "unknown") {
    if ($fname =~ /extern\/goocanvasmm\/goocanvasmm/) {
        $policy = "LGPLv2.1 or later";
    }
}

$copyright =~ s/\s+$//g;
$copyright =~ s/^\s+//g;
$copyright =~ s/©/\(C\)/g;
$copyright =~ s/\xa9/\(C\)/g;
$policy =~ s/\s+$//g;
$policy =~ s/^\s+//g;

$copyright =~ s/Alex Bernardino/Alexandre Bernardino/;

if ($copyright eq "default") {
    # no copyright statement - only accept for example code
    # update: now putting copyright statement in example code
    #if (!($fname =~ /example\//)) {
    $copyright = "unknown";
    $report = "skipped";
    #}
}

if ($policy ne "default" || $copyright ne "default") {
    $report = "CopyPolicy [$policy] Copyright [$copyright]";
}

if ($policy eq "default") {
    $policy = "unknown";
}

if ($policy eq "Released under the terms of the LGPLv2.1 or later, see LGPL.TXT") {
    $policy = "LGPLv2.1 or later";
}

if ($policy eq "Released under the terms of the GNU GPL version 2") {
    $policy = "GPLv2";
}

if ($policy eq "Released under the terms of the GNU GPL v2.0.") {
    $policy = "GPLv2";
}

$txt2 = $txt;

if ($report ne "skipped") {
    my $authortxt = "";
    if ($authors ne "") {
        $authortxt = "  Authors: $authors\n";
    }
    my $txt = "$fname\n  Copyright: $copyright\n$authortxt  CopyPolicy: $policy\n\n";
    open(FOUT,">>license-changes.txt");
    print FOUT $txt;
    close(FOUT);
    if ($policy =~ /LGPLv2.1 or later/) {
        open(FOUT,">>license-good.txt");
        print FOUT $txt;
        close(FOUT);
    } else {
        open(FOUT,">>license-odd.txt");
        print FOUT $txt;
        close(FOUT);
    }
}

if ($txt ne $txt2) {
    open(FOUT,">$fname.shadow");
    print FOUT $txt2;
    close(FOUT);
    system "echo should have changed $fname >> license-changes.txt";
    #system "emacs $fname &";
} else {
#    system "echo \"$report $fname\" >> license-changes.txt";
}
