#!/bin/bash


export BUNDLE_YARP_VERSION=2.3.3
export BUNDLE_YARP_REVISION=8565  # just for testing

export BUNDLE_ACE_VERSION=6.0.1
export BUNDLE_CMAKE_VERSION=2.8.4
export BUNDLE_NSIS_VERSION=2.46
export BUNDLE_GSL_VERSION=1.14
export BUNDLE_GTKMM_VERSION=2.22.0-2
