#!/bin/bash
export BUNDLE_YARP_VERSION=2.3.64
export BUNDLE_TWEAK=1
export BUNDLE_ACE_VERSION=6.1.1
export BUNDLE_CMAKE_VERSION=3.1.3
export BUNDLE_NSIS_VERSION=2.46
export BUNDLE_GSL_VERSION=1.14
export BUNDLE_EXT_REPO_URL=http://www.icub.org/download/software/windows/common
# Empty version means no support, yarp will be compiled without it
export BUNDLE_QT_VERSION_v10_x86=5.4.1
export BUNDLE_QT_VERSION_v10_x86_amd64=
export BUNDLE_QT_VERSION_v11_x86=5.4.1
export BUNDLE_QT_VERSION_v11_x86_amd64=5.2.1
export BUNDLE_QT_VERSION_v12_x86=5.4.1
export BUNDLE_QT_VERSION_v12_x86_amd64=5.4.1
export BUNDLE_GTKMM_VERSION_v10_x86=2.22.0
export BUNDLE_GTKMM_VERSION_v10_x86_amd64=2.22.0
export BUNDLE_GTKMM_VERSION_v11_x86=2.22.0
export BUNDLE_GTKMM_VERSION_v11_x86_amd64=2.22.0
export BUNDLE_GTKMM_VERSION_v12_x86=
export BUNDLE_GTKMM_VERSION_v12_x86_amd64=
YARP_CMAKE_OPTIONS="\
 -DCREATE_YARPMANAGER_CONSOLE=TRUE \
 -DCREATE_YARPMANAGER=TRUE \
 -DCREATE_LIB_MATH=TRUE \
 -DCREATE_GUIS=TRUE \
 -DCREATE_SHARED_LIBRARY=TRUE \
 -DYARP_COMPILE_TESTS=FALSE \
 -DYARP_FILTER_API=TRUE \
 -DCREATE_IDLS=TRUE \
 -DENABLE_yarpidl_thrift=TRUE \
 -DCREATE_OPTIONAL_CARRIERS=TRUE \
 -DENABLE_yarpcar_tcpros_carrier=TRUE \
 -DENABLE_yarpcar_xmlrpc_carrier=TRUE \
 -DENABLE_yarpcar_bayer_carrier=TRUE \
 -DUSE_LIBDC1394=FALSE \
 -DENABLE_yarpcar_priority_carrier=TRUE"
 