#!/bin/bash

# SPDX-FileCopyrightText: 2006-2021 Istituto Italiano di Tecnologia (IIT)
# SPDX-FileCopyrightText: 2006-2010 RobotCub Consortium
# SPDX-License-Identifier: BSD-3-Clause

echo " "
echo Make sure yarp server is running.
echo This script hits it with lots of registers/unregisters
echo " "


while true; do
    # can pass "verbose" as $1 if desired
    yarp $1 name register /foo
    yarp $1 name unregister /foo

    # even more basic test
    #    echo "blahlah" | telnet localhost 10000
    #    sleep 1

done
