/*
 * SPDX-FileCopyrightText: 2006-2021 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: BSD-3-Clause
 */

// Autogenerated by Thrift Compiler (0.14.1-yarped)
//
// This is an automatically generated file.
// It could get re-generated if the ALLOW_IDL_GENERATION flag is on.

#ifndef YARP_THRIFT_GENERATOR_SERVICE_YARPAUDIOPLAYER_IDL_H
#define YARP_THRIFT_GENERATOR_SERVICE_YARPAUDIOPLAYER_IDL_H

#include <yarp/os/Wire.h>
#include <yarp/os/idl/WireTypes.h>
#include <yarp/os/ApplicationNetworkProtocolVersion.h>

/**
 * yarpAudioPlayer_IDL
 * Interface.
 */
class yarpAudioPlayer_IDL :
        public yarp::os::Wire
{
public:
    //ProtocolVersion
    virtual yarp::os::ApplicationNetworkProtocolVersion getLocalProtocolVersion();
    virtual yarp::os::ApplicationNetworkProtocolVersion getRemoteProtocolVersion();
    virtual bool checkProtocolVersion();

    // Constructor
    yarpAudioPlayer_IDL();

    //Service methods
    /**
     * Play the given audio file
     * @return true/false on success/failure
     */
    virtual bool play(const std::string& filename);

    /**
     * Generate and send a test sound
     * @param type can be "sine" , "sawtooth"  , "squarewave"
     * @param duration the duration of the sound in seconds
     * @param frequency the signal in hertz
     * @param amplitude the amplitude of the signal (16 bit)
     * @param channels number of channels
     * @param sampling_rate signal sampling rate (samples/s)
     * @return true/false on success/failure
     */
    virtual bool test(const std::string& type = "sine", const double duration = 1, const double frequency = 440, const std::int16_t amplitude = 30000, const std::int16_t sampling_rate = 16000, const std::int16_t channels = 1);

    // help method
    virtual std::vector<std::string> help(const std::string& functionName = "--all");

    // read from ConnectionReader
    bool read(yarp::os::ConnectionReader& connection) override;
};

#endif // YARP_THRIFT_GENERATOR_SERVICE_YARPAUDIOPLAYER_IDL_H
