/*
 * SPDX-FileCopyrightText: 2006-2021 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: BSD-3-Clause
 */

// Autogenerated by Thrift Compiler (0.14.1-yarped)
//
// This is an automatically generated file.
// It could get re-generated if the ALLOW_IDL_GENERATION flag is on.

#ifndef YARP_THRIFT_GENERATOR_STRUCT_MATRIXDATA_H
#define YARP_THRIFT_GENERATOR_STRUCT_MATRIXDATA_H

#include <yarp/sig/api.h>

#include <yarp/os/Wire.h>
#include <yarp/os/idl/WireTypes.h>

namespace yarp::sig {

class YARP_sig_API MatrixData :
        public yarp::os::idl::WirePortable
{
protected:
    // Fields
    std::int32_t nrows{0};
    std::int32_t ncols{0};
    std::vector<double> storage{};

public:
    // Default constructor
    MatrixData() = default;

    // Constructor with field values
    MatrixData(const std::int32_t nrows,
               const std::int32_t ncols,
               const std::vector<double>& storage);

    // Read structure on a Wire
    bool read(yarp::os::idl::WireReader& reader) override;

    // Read structure on a Connection
    bool read(yarp::os::ConnectionReader& connection) override;

    // Write structure on a Wire
    bool write(const yarp::os::idl::WireWriter& writer) const override;

    // Write structure on a Connection
    bool write(yarp::os::ConnectionWriter& connection) const override;

    // Convert to a printable string
    std::string toString() const;

    // If you want to serialize this class without nesting, use this helper
    typedef yarp::os::idl::Unwrapped<MatrixData> unwrapped;

private:
    // read/write nrows field
    bool read_nrows(yarp::os::idl::WireReader& reader);
    bool write_nrows(const yarp::os::idl::WireWriter& writer) const;
    bool nested_read_nrows(yarp::os::idl::WireReader& reader);
    bool nested_write_nrows(const yarp::os::idl::WireWriter& writer) const;

    // read/write ncols field
    bool read_ncols(yarp::os::idl::WireReader& reader);
    bool write_ncols(const yarp::os::idl::WireWriter& writer) const;
    bool nested_read_ncols(yarp::os::idl::WireReader& reader);
    bool nested_write_ncols(const yarp::os::idl::WireWriter& writer) const;

    // read/write storage field
    bool read_storage(yarp::os::idl::WireReader& reader);
    bool write_storage(const yarp::os::idl::WireWriter& writer) const;
    bool nested_read_storage(yarp::os::idl::WireReader& reader);
    bool nested_write_storage(const yarp::os::idl::WireWriter& writer) const;
};

} // namespace yarp::sig

#endif // YARP_THRIFT_GENERATOR_STRUCT_MATRIXDATA_H
