/*
 * SPDX-FileCopyrightText: 2006-2021 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: BSD-3-Clause
 */

// Autogenerated by Thrift Compiler (0.14.1-yarped)
//
// This is an automatically generated file.
// It could get re-generated if the ALLOW_IDL_GENERATION flag is on.

#ifndef YARP_THRIFT_GENERATOR_STRUCT_MEMORYINFODATA_H
#define YARP_THRIFT_GENERATOR_STRUCT_MEMORYINFODATA_H

#include <yarp/os/api.h>

#include <yarp/os/Wire.h>
#include <yarp/os/idl/WireTypes.h>

namespace yarp::os {

/**
 * @brief Holds the system memory information
 */
class YARP_os_API MemoryInfoData :
        public yarp::os::idl::WirePortable
{
public:
    // Fields
    std::int32_t totalSpace{0};
    std::int32_t freeSpace{0};

    // Default constructor
    MemoryInfoData() = default;

    // Constructor with field values
    MemoryInfoData(const std::int32_t totalSpace,
                   const std::int32_t freeSpace);

    // Read structure on a Wire
    bool read(yarp::os::idl::WireReader& reader) override;

    // Read structure on a Connection
    bool read(yarp::os::ConnectionReader& connection) override;

    // Write structure on a Wire
    bool write(const yarp::os::idl::WireWriter& writer) const override;

    // Write structure on a Connection
    bool write(yarp::os::ConnectionWriter& connection) const override;

    // Convert to a printable string
    std::string toString() const;

    // If you want to serialize this class without nesting, use this helper
    typedef yarp::os::idl::Unwrapped<MemoryInfoData> unwrapped;

private:
    // read/write totalSpace field
    bool read_totalSpace(yarp::os::idl::WireReader& reader);
    bool write_totalSpace(const yarp::os::idl::WireWriter& writer) const;
    bool nested_read_totalSpace(yarp::os::idl::WireReader& reader);
    bool nested_write_totalSpace(const yarp::os::idl::WireWriter& writer) const;

    // read/write freeSpace field
    bool read_freeSpace(yarp::os::idl::WireReader& reader);
    bool write_freeSpace(const yarp::os::idl::WireWriter& writer) const;
    bool nested_read_freeSpace(yarp::os::idl::WireReader& reader);
    bool nested_write_freeSpace(const yarp::os::idl::WireWriter& writer) const;
};

} // namespace yarp::os

#endif // YARP_THRIFT_GENERATOR_STRUCT_MEMORYINFODATA_H
