/*
 * SPDX-FileCopyrightText: 2006-2021 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: BSD-3-Clause
 */

// Autogenerated by Thrift Compiler (0.14.1-yarped)
//
// This is an automatically generated file.
// It could get re-generated if the ALLOW_IDL_GENERATION flag is on.

#include <yarp/os/ProcessInfoData.h>

namespace yarp::os {

// Constructor with field values
ProcessInfoData::ProcessInfoData(const std::string& name,
                                 const std::string& arguments,
                                 const std::int32_t schedPolicy,
                                 const std::int32_t schedPriority,
                                 const std::int32_t pid) :
        WirePortable(),
        name(name),
        arguments(arguments),
        schedPolicy(schedPolicy),
        schedPriority(schedPriority),
        pid(pid)
{
}

// Read structure on a Wire
bool ProcessInfoData::read(yarp::os::idl::WireReader& reader)
{
    if (!read_name(reader)) {
        return false;
    }
    if (!read_arguments(reader)) {
        return false;
    }
    if (!read_schedPolicy(reader)) {
        return false;
    }
    if (!read_schedPriority(reader)) {
        return false;
    }
    if (!read_pid(reader)) {
        return false;
    }
    if (reader.isError()) {
        return false;
    }
    return true;
}

// Read structure on a Connection
bool ProcessInfoData::read(yarp::os::ConnectionReader& connection)
{
    yarp::os::idl::WireReader reader(connection);
    if (!reader.readListHeader(5)) {
        return false;
    }
    if (!read(reader)) {
        return false;
    }
    return true;
}

// Write structure on a Wire
bool ProcessInfoData::write(const yarp::os::idl::WireWriter& writer) const
{
    if (!write_name(writer)) {
        return false;
    }
    if (!write_arguments(writer)) {
        return false;
    }
    if (!write_schedPolicy(writer)) {
        return false;
    }
    if (!write_schedPriority(writer)) {
        return false;
    }
    if (!write_pid(writer)) {
        return false;
    }
    if (writer.isError()) {
        return false;
    }
    return true;
}

// Write structure on a Connection
bool ProcessInfoData::write(yarp::os::ConnectionWriter& connection) const
{
    yarp::os::idl::WireWriter writer(connection);
    if (!writer.writeListHeader(5)) {
        return false;
    }
    if (!write(writer)) {
        return false;
    }
    return true;
}

// Convert to a printable string
std::string ProcessInfoData::toString() const
{
    yarp::os::Bottle b;
    if (!yarp::os::Portable::copyPortable(*this, b)) {
        return {};
    }
    return b.toString();
}

// read name field
bool ProcessInfoData::read_name(yarp::os::idl::WireReader& reader)
{
    if (reader.noMore()) {
        reader.fail();
        return false;
    }
    if (!reader.readString(name)) {
        reader.fail();
        return false;
    }
    return true;
}

// write name field
bool ProcessInfoData::write_name(const yarp::os::idl::WireWriter& writer) const
{
    if (!writer.writeString(name)) {
        return false;
    }
    return true;
}

// read (nested) name field
bool ProcessInfoData::nested_read_name(yarp::os::idl::WireReader& reader)
{
    if (reader.noMore()) {
        reader.fail();
        return false;
    }
    if (!reader.readString(name)) {
        reader.fail();
        return false;
    }
    return true;
}

// write (nested) name field
bool ProcessInfoData::nested_write_name(const yarp::os::idl::WireWriter& writer) const
{
    if (!writer.writeString(name)) {
        return false;
    }
    return true;
}

// read arguments field
bool ProcessInfoData::read_arguments(yarp::os::idl::WireReader& reader)
{
    if (reader.noMore()) {
        reader.fail();
        return false;
    }
    if (!reader.readString(arguments)) {
        reader.fail();
        return false;
    }
    return true;
}

// write arguments field
bool ProcessInfoData::write_arguments(const yarp::os::idl::WireWriter& writer) const
{
    if (!writer.writeString(arguments)) {
        return false;
    }
    return true;
}

// read (nested) arguments field
bool ProcessInfoData::nested_read_arguments(yarp::os::idl::WireReader& reader)
{
    if (reader.noMore()) {
        reader.fail();
        return false;
    }
    if (!reader.readString(arguments)) {
        reader.fail();
        return false;
    }
    return true;
}

// write (nested) arguments field
bool ProcessInfoData::nested_write_arguments(const yarp::os::idl::WireWriter& writer) const
{
    if (!writer.writeString(arguments)) {
        return false;
    }
    return true;
}

// read schedPolicy field
bool ProcessInfoData::read_schedPolicy(yarp::os::idl::WireReader& reader)
{
    if (reader.noMore()) {
        reader.fail();
        return false;
    }
    if (!reader.readI32(schedPolicy)) {
        reader.fail();
        return false;
    }
    return true;
}

// write schedPolicy field
bool ProcessInfoData::write_schedPolicy(const yarp::os::idl::WireWriter& writer) const
{
    if (!writer.writeI32(schedPolicy)) {
        return false;
    }
    return true;
}

// read (nested) schedPolicy field
bool ProcessInfoData::nested_read_schedPolicy(yarp::os::idl::WireReader& reader)
{
    if (reader.noMore()) {
        reader.fail();
        return false;
    }
    if (!reader.readI32(schedPolicy)) {
        reader.fail();
        return false;
    }
    return true;
}

// write (nested) schedPolicy field
bool ProcessInfoData::nested_write_schedPolicy(const yarp::os::idl::WireWriter& writer) const
{
    if (!writer.writeI32(schedPolicy)) {
        return false;
    }
    return true;
}

// read schedPriority field
bool ProcessInfoData::read_schedPriority(yarp::os::idl::WireReader& reader)
{
    if (reader.noMore()) {
        reader.fail();
        return false;
    }
    if (!reader.readI32(schedPriority)) {
        reader.fail();
        return false;
    }
    return true;
}

// write schedPriority field
bool ProcessInfoData::write_schedPriority(const yarp::os::idl::WireWriter& writer) const
{
    if (!writer.writeI32(schedPriority)) {
        return false;
    }
    return true;
}

// read (nested) schedPriority field
bool ProcessInfoData::nested_read_schedPriority(yarp::os::idl::WireReader& reader)
{
    if (reader.noMore()) {
        reader.fail();
        return false;
    }
    if (!reader.readI32(schedPriority)) {
        reader.fail();
        return false;
    }
    return true;
}

// write (nested) schedPriority field
bool ProcessInfoData::nested_write_schedPriority(const yarp::os::idl::WireWriter& writer) const
{
    if (!writer.writeI32(schedPriority)) {
        return false;
    }
    return true;
}

// read pid field
bool ProcessInfoData::read_pid(yarp::os::idl::WireReader& reader)
{
    if (reader.noMore()) {
        reader.fail();
        return false;
    }
    if (!reader.readI32(pid)) {
        reader.fail();
        return false;
    }
    return true;
}

// write pid field
bool ProcessInfoData::write_pid(const yarp::os::idl::WireWriter& writer) const
{
    if (!writer.writeI32(pid)) {
        return false;
    }
    return true;
}

// read (nested) pid field
bool ProcessInfoData::nested_read_pid(yarp::os::idl::WireReader& reader)
{
    if (reader.noMore()) {
        reader.fail();
        return false;
    }
    if (!reader.readI32(pid)) {
        reader.fail();
        return false;
    }
    return true;
}

// write (nested) pid field
bool ProcessInfoData::nested_write_pid(const yarp::os::idl::WireWriter& writer) const
{
    if (!writer.writeI32(pid)) {
        return false;
    }
    return true;
}

} // namespace yarp::os
