/*
 * SPDX-FileCopyrightText: 2006-2021 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: BSD-3-Clause
 */

// Autogenerated by Thrift Compiler (0.14.1-yarped)
//
// This is an automatically generated file.
// It could get re-generated if the ALLOW_IDL_GENERATION flag is on.

#include <yarp/os/StampData.h>

namespace yarp::os {

// Constructor with field values
StampData::StampData(const std::int32_t sequenceNumber,
                     const double timeStamp) :
        WirePortable(),
        sequenceNumber(sequenceNumber),
        timeStamp(timeStamp)
{
}

// Read structure on a Wire
bool StampData::read(yarp::os::idl::WireReader& reader)
{
    if (!read_sequenceNumber(reader)) {
        return false;
    }
    if (!read_timeStamp(reader)) {
        return false;
    }
    if (reader.isError()) {
        return false;
    }
    return true;
}

// Read structure on a Connection
bool StampData::read(yarp::os::ConnectionReader& connection)
{
    yarp::os::idl::WireReader reader(connection);
    if (!reader.readListHeader(2)) {
        return false;
    }
    if (!read(reader)) {
        return false;
    }
    return true;
}

// Write structure on a Wire
bool StampData::write(const yarp::os::idl::WireWriter& writer) const
{
    if (!write_sequenceNumber(writer)) {
        return false;
    }
    if (!write_timeStamp(writer)) {
        return false;
    }
    if (writer.isError()) {
        return false;
    }
    return true;
}

// Write structure on a Connection
bool StampData::write(yarp::os::ConnectionWriter& connection) const
{
    yarp::os::idl::WireWriter writer(connection);
    if (!writer.writeListHeader(2)) {
        return false;
    }
    if (!write(writer)) {
        return false;
    }
    return true;
}

// Convert to a printable string
std::string StampData::toString() const
{
    yarp::os::Bottle b;
    if (!yarp::os::Portable::copyPortable(*this, b)) {
        return {};
    }
    return b.toString();
}

// read sequenceNumber field
bool StampData::read_sequenceNumber(yarp::os::idl::WireReader& reader)
{
    if (reader.noMore()) {
        reader.fail();
        return false;
    }
    if (!reader.readI32(sequenceNumber)) {
        reader.fail();
        return false;
    }
    return true;
}

// write sequenceNumber field
bool StampData::write_sequenceNumber(const yarp::os::idl::WireWriter& writer) const
{
    if (!writer.writeI32(sequenceNumber)) {
        return false;
    }
    return true;
}

// read (nested) sequenceNumber field
bool StampData::nested_read_sequenceNumber(yarp::os::idl::WireReader& reader)
{
    if (reader.noMore()) {
        reader.fail();
        return false;
    }
    if (!reader.readI32(sequenceNumber)) {
        reader.fail();
        return false;
    }
    return true;
}

// write (nested) sequenceNumber field
bool StampData::nested_write_sequenceNumber(const yarp::os::idl::WireWriter& writer) const
{
    if (!writer.writeI32(sequenceNumber)) {
        return false;
    }
    return true;
}

// read timeStamp field
bool StampData::read_timeStamp(yarp::os::idl::WireReader& reader)
{
    if (reader.noMore()) {
        reader.fail();
        return false;
    }
    if (!reader.readFloat64(timeStamp)) {
        reader.fail();
        return false;
    }
    return true;
}

// write timeStamp field
bool StampData::write_timeStamp(const yarp::os::idl::WireWriter& writer) const
{
    if (!writer.writeFloat64(timeStamp)) {
        return false;
    }
    return true;
}

// read (nested) timeStamp field
bool StampData::nested_read_timeStamp(yarp::os::idl::WireReader& reader)
{
    if (reader.noMore()) {
        reader.fail();
        return false;
    }
    if (!reader.readFloat64(timeStamp)) {
        reader.fail();
        return false;
    }
    return true;
}

// write (nested) timeStamp field
bool StampData::nested_write_timeStamp(const yarp::os::idl::WireWriter& writer) const
{
    if (!writer.writeFloat64(timeStamp)) {
        return false;
    }
    return true;
}

} // namespace yarp::os
