/*
 * SPDX-FileCopyrightText: 2006-2021 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef YARP_DEV_CONTROLBOARDWRAPPER_CONTROLBOARDWRAPPERLOGCOMPONENT_H
#define YARP_DEV_CONTROLBOARDWRAPPER_CONTROLBOARDWRAPPERLOGCOMPONENT_H

#include <yarp/os/LogComponent.h>

YARP_DECLARE_LOG_COMPONENT(CONTROLBOARD)

#endif // YARP_DEV_CONTROLBOARDWRAPPER_CONTROLBOARDWRAPPERLOGCOMPONENT_H
