#!/bin/bash

# Copyright: (C) 2010 RobotCub Consortium
# Author: Paul Fitzpatrick
# CopyPolicy: Released under the terms of the LGPLv2.1 or later, see LGPL.TXT

# run as ./scripts/autocheck-doc.sh

# now that our web server is local there's no reason not
# to rebuild the documentation as often as the code changes
if [ "k$1" = "kforce" ] ; then
    rm build-doc.txt
fi

touch build-doc.txt
cat conf/build.txt | grep DOC | tee build-doc-new.txt
cmp build-doc-new.txt build-doc.txt || (
	# update packages
	./scripts/update-doc
	./scripts/update-web
)
cp build-doc-new.txt build-doc.txt
