#!/bin/bash

# run as ./scripts/make-autoconf-package

ORG=$PWD
SRC=$PWD/source-package
BASE=$PWD/autoconf-package

echo "Make sure you run ./scripts/make-source-package first"

rm -rf $BASE
mkdir -p $BASE

for f in `ls $SRC/*.tar.gz`; do
   echo Working with $f
    rm -rf $BASE
    mkdir -p $BASE
    cd $BASE
    tar xzf - < $f
    dir=`basename $f .tar.gz`
    ver=`echo $dir | sed s/.*-//g`
    echo "Version number is $ver"
    if [ -e $dir ]; then
	echo Working in $dir
	cd $dir
	./bootstrap.sh
	./configure
	make distcheck
	cp *.tar.gz ..
    fi
done

echo "Results in $BASE"
