#!/bin/sh

echo "This script is no longer needed"
echo "Man pages are built using doxygen"
echo "run ./scripts/update-doc"
exit 0

which docbook-to-man || {
    echo "Need docbook-to-man for manpages"
    exit 1
}

for f in `find . -iname "*.sgml"`; do
    out=`basename $f .sgml`.1
    echo Generating $out from $f
    docbook-to-man $f > $out
done
