#!/bin/bash

# run as ./scripts/make-source-package

ORG=$PWD
BASE=$PWD/source-package

#mkdir -p $BASE/repository

rm -rf $BASE/repository
cd $BASE/
svn co https://yarp0.svn.sourceforge.net/svnroot/yarp0/trunk/yarp2 repository

#if [ ! -e $BASE/repository/CVS ]; then
#    cp -R CVS $BASE/repository/CVS
#fi

# skip cvs update if nocvs specified
#if [ ! "nocvs" = "$1" ]; then
#    echo "CVS update"
#    cd $BASE/repository
#    cvs update -d
#
#fi


rm -rf $BASE/pruned-repository
cp -R $BASE/repository $BASE/pruned-repository
cd $BASE/pruned-repository
want_prune=true

if $want_prune; then
    echo "Directories removed for distribution:" > /tmp/REMOVED
    # certain driver directories are of ambiguous redistribution status
    for f in src/modules/dimax_u2c/blob; do
	mydir=$PWD
	cd $f
	( ls -l `find . -type f | grep -v .svn` ) > /tmp/inventory.txt
	cd $mydir
	echo "  Removed: $f" >> /tmp/REMOVED
	rm -rf $f
	mkdir -p $f
	(
	    echo "Contents of this directory are not known to be redistributable"
	    echo "What should be here:"
	    cat /tmp/inventory.txt
	) > $f/README.TXT
    done

    for f in debian ; do
	echo "  For future downstream convenience, removed: $f" >> /tmp/REMOVED
	rm -rf $f
    done
    (
	cat src/modules/CMakeLists.txt | grep -v dimax
    ) > /tmp/CMakeLists.txt
    cp /tmp/CMakeLists.txt src/modules
    cp /tmp/REMOVED .
    ./scripts/update-license
    cp license-statement.txt COPYING
    rm -f license-*.txt
fi


rm -rf $BASE/pack
rm -f $BASE/*.tar.gz
mkdir -p $BASE/pack
cd $BASE/pack
OS=`uname -o`
if [ "k$OS" = "kCygwin" ]; then
	if [ "k$ACE_ROOT" = "k" ]; then
		ACE_ROOT=`cygpath -w $ORG/../ACE_wrappers`
	fi
	echo "ACE_ROOT is $ACE_ROOT"
	export ACE_ROOT=$ACE_ROOT
	GEN="NMake Makefiles"
	CMAKE="/cygdrive/c/Program Files/CMake 2.6/bin/cmake.exe"
	"$CMAKE" -G "$GEN" ../pruned-repository
	nmake package_source
	rm -f $BASE/*.zip
	cp *.zip $BASE
	echo Source package is $BASE/*.zip
else
	cmake ../pruned-repository
	make package_source
	rm -f $BASE/*.tar.gz
	cp *.tar.gz $BASE
	echo Source package is $BASE/*.tar.gz
fi


