#!/bin/sh

# This script makes a debian package
# call from root as ./scripts/make-debian

echo "Warning: I am running cmake to set a temporary install path!"

WORK="$PWD/tmp-deb"
rm -rf $WORK

cmake -DCMAKE_INSTALL_PREFIX:PATH=$WORK .

make && make install
cp -R $WORK/usr/share/doc/yarp/DEBIAN $WORK/DEBIAN
NAME=`grep -i "Package:" $WORK/DEBIAN/control | sed "s/.* //"`
VERSION=`grep -i "Version:" $WORK/DEBIAN/control | sed "s/.* //"`
dpkg --build $WORK $NAME-$VERSION.deb



