#!/bin/bash

# run as ./scripts/make-source-package

ORG=$PWD
BASE=$PWD/source-package

mkdir -p $BASE/repository

if [ ! -e $BASE/repository/CVS ]; then
    cp -R CVS $BASE/repository/CVS
fi

# skip cvs update if nocvs specified
if [ ! "nocvs" = "$1" ]; then
    echo "CVS update"
    cd $BASE/repository
    cvs update -d
fi

rm -rf $BASE/pack
rm -f $BASE/*.tar.gz
mkdir -p $BASE/pack
cd $BASE/pack
OS=`uname -o`
if [ "k$OS" = "kCygwin" ]; then
	if [ "k$ACE_ROOT" = "k" ]; then
		ACE_ROOT=`cygpath -w $ORG/../ACE_wrappers`
	fi
	echo "ACE_ROOT is $ACE_ROOT"
	GEN="NMake Makefiles"
	CMAKE="/cygdrive/c/Program Files/CMake 2.4/bin/cmake.exe"
	"$CMAKE" -G "$GEN" ../repository
	nmake package_source
	cp *.zip $BASE
	echo Source package is $BASE/*.zip
else
	cmake ../repository
	make package_source
	cp *.tar.gz $BASE
	echo Source package is $BASE/*.tar.gz
fi


