#!/bin/bash

echo On a debian machine, get all packages needed

#gtk
sudo apt-get install libgtk2.0-dev pkg-config

# ffmpeg
sudo apt-get install libavformat-dev libavcodec-dev libavifile-0.7-dev

# portaudio
sudo apt-get install portaudio19-dev

