#!/bin/bash

# Copyright: (C) 2010 RobotCub Consortium
# Author: Paul Fitzpatrick
# CopyPolicy: Released under the terms of the LGPLv2.1 or later, see LGPL.TXT

echo On a debian machine, get all packages needed

# gtk
sudo apt-get install libgtk2.0-dev pkg-config

# ffmpeg
sudo apt-get install libavformat-dev libavcodec-dev libavifile-0.7-dev

# portaudio
sudo apt-get install portaudio19-dev

# opencv
sudo apt-get install libcv-dev libhighgui-dev libcvaux-dev
