#!/usr/bin/perl -w

my $fname = $ARGV[0];

print "$fname\n";

my $txt = "";
open(FIN,"<$fname");
while (<FIN>) {
    $txt .= $_;
}
close(FIN);

my $report = "skipped";

my $policy = "unknown";
my $copyright = "unknown";

my $quiet = 1;
if ($txt=~/license/i || $txt=~/copyright/i || $txt=~/rights/i) {
    $quiet = 0;
}

if ($txt=~/academic free/i || $quiet) {
    if (!($txt=~/CopyPolicy/)) {
	$policy = "default";
	$copyright = "default";
    }
}


if ($txt =~ /license/i || $txt =~ /copyright/i) {
}
 
if ($txt=~/CopyPolicy\:\s*(.*)/i) {
    $policy = $1;
}

if ($copyright eq "unknown") {
    if ($txt=~/copyright\:\s*([^\"\'\*\r\n]+)\s*[\n\r\*]/i) {
	$copyright = $1;
    } elsif ($txt =~ /copyright\:?\s*([^\(0-9][^\"\'\*\r\n]+)\s*[\n\r\*]/i) {
	$copyright = $1;
    }    
}

$copyright =~ s/\s+$//g;
$copyright =~ s/^\s+//g;
$copyright =~ s/\xa9/\(C\)/g;
$policy =~ s/\s+$//g;
$policy =~ s/^\s+//g;


if ($policy ne "default" || $copyright ne "default") {
    $report = "CopyPolicy [$policy] Copyright [$copyright]";
}

$txt2 = $txt;

#system "echo \"$report $fname\" >> license-changes.txt";
if ($report ne "skipped") {
    my $txt = "$fname\n\tCopyright: $copyright\n\tCopyPolicy: $policy\n\n";
    open(FOUT,">>license-changes.txt");
    print FOUT $txt;
    close(FOUT);
}


if (0) {
    if ($txt ne $txt2) {
	#open(FOUT,">$fname");
	#print FOUT $txt;
	#close(FOUT);
	system "echo changed $fname >> license-changes.txt";
    } else {
	system "echo \"$report $fname\" >> license-changes.txt";
    }
}


