#!/bin/sh

echo "Puts license text in order."
echo "Make sure you run this as ./scripts/update-license"

# reset change log
echo -n | tee license-changes.txt

for f in `find . -iname "*.h"; find . -iname "*.cpp"; find . -iname "*.c"`; do
    #ignore=`echo "$f" | grep -q dd_orig && echo true || echo false`
    ignore=false
    if $ignore ; then
	echo ignored $f >> license-changes.txt
    else
	./scripts/update-license-single $f
    fi
done




