#!/usr/bin/perl -w

use strict;

my $dir = $ARGV[0];

my $skip = 0;
while (<STDIN>) {
    chomp($_);
    if ($_ eq "") {
	$skip = 0;
    }
    if (!$skip) {
	print "$_\n";
    }
    if ($_ =~ /^\# automake_expand ([^ ]+) (.*)/) {
	my $var = $1;
	my $card = $2;
	my $fnames = `cd $dir; ls $card 2> /dev/null`;
	$fnames =~ s/[\n\r]/ /g;
	print "$var = $fnames\n";
	$skip = 1;
    }
}

