#!/usr/bin/perl -w

my $fname = $ARGV[0];


my $std_license = "
/*
 * Copyright (C) 2006 Author McAuthor
 * CopyPolicy: Released under the terms of the GNU GPL v2.0.
 *
 */
";


print "$fname\n";

my $txt = "";
open(FIN,"<$fname");
while (<FIN>) {
    $txt .= $_;
}
close(FIN);

my $report = "skipped";

my $policy = "unknown";
my $copyright = "unknown";

my $quiet = 1;
if ($txt=~/license/i || $txt=~/copyright/i || $txt=~/rights/i) {
    $quiet = 0;
}

if ($txt=~/academic free/i || $quiet) {
    if (!($txt=~/CopyPolicy/)) {
	$policy = "default";
	$copyright = "default";
    }
}


if ($txt =~ /license/i || $txt =~ /copyright/i) {
}

$txt =~ s/.*GNU General Public License, version 2 or.*/CopyPolicy: Released under the terms of the GNU GPL v2.0./;
 
if ($txt=~/CopyPolicy\:\s*(.*)/i) {
    $policy = $1;
}

if ($copyright eq "unknown") {
    if ($txt=~/copyright\:\s*([^\"\'\*\r\n]+)\s*[\n\r\*]/i) {
	$copyright = $1;
    } elsif ($txt =~ /copyright\:?\s*([^\(0-9][^\"\'\*\r\n]+)\s*[\n\r\*]/i) {
	$copyright = $1;
    }    
}

$copyright =~ s/\s+$//g;
$copyright =~ s/^\s+//g;
$copyright =~ s/\xa9/\(C\)/g;
$policy =~ s/\s+$//g;
$policy =~ s/^\s+//g;


if ($copyright eq "default") {
    # no copyright statement - only accept for example code
    if (!($fname =~ /example\//)) {
	$copyright = "unknown";
	$report = "skipped";
    }
}

if ($policy ne "default" || $copyright ne "default") {
    $report = "CopyPolicy [$policy] Copyright [$copyright]";
}

if ($policy eq "default") {
    $policy = "unknown";
}

$txt2 = $txt;

#if ($policy =~ /GNU GPL/) {
#    $report = "skipped";
#}

#system "echo \"$report $fname\" >> license-changes.txt";
if ($report ne "skipped") {
    my $txt = "$fname\n  Copyright: $copyright\n  CopyPolicy: $policy\n\n";
    open(FOUT,">>license-changes.txt");
    print FOUT $txt;
    close(FOUT);
    if ($policy =~ /GNU GPL v2.0/) {
	open(FOUT,">>license-good.txt");
	print FOUT $txt;
	close(FOUT);
    } else {
	open(FOUT,">>license-odd.txt");
	print FOUT $txt;
	close(FOUT);
    }
}

if (0) {
    if ($copyright eq "default") {
	# no copyright information -> guess who wrote it
	my $ok = 1;
	if ($fname =~ /example\//) {
	    $ok = 1;
	}
	my $authors = "Paul Fitzpatrick";
	#my $authors = "Giorgio Metta";
	if ($ok) {
	    open(FOUT,">>license-changes.txt");
	    print FOUT "$fname needs copyright statement\n";
	    print FOUT "$fname author $authors\n";
	    close(FOUT);
	    
	    my $replacement = $std_license;
	    $replacement =~ s/Author McAuthor/$authors/;
	    
	    $txt2 =~ s/(\-\*\-\n)/$1$replacement\n/;
	}
    }
}



if (0) { # don't need to scrub AFL anymore
    if ($txt =~ /Academic Free License/) {
	my $authors = "paulfitz";
	if ($txt =~ /\/\/\/.*\#(.*)\#/) {
	    $authors = $1;
	}
	
	$authors =~ s/Add our.*/paulfitz, pasa/;
	$authors =~ s/paulfitz/Paul Fitzpatrick/;
	$authors =~ s/pasa/Giorgio Metta/;
	
	open(FOUT,">>license-changes.txt");
	print FOUT "$fname needs AFL stripped\n";
	print FOUT "$fname author $authors\n";
	close(FOUT);
	
	$replacement = $std_license;
	$replacement =~ s/Author McAuthor/$authors/;
	
#    $txt2 =~ s/\/\/\/\/\/\/\/\/\/(.|[\n\r])*Rosen(.|[\n\r])*Licensed under the Academic.*\n+(\/\/\/\n)*/$replacement/;
#    $txt2 =~ s/\/\/\/\/\/\/\/\/\/(.|[\n\r])*YARP_ROOT.conf(.|[\n\r])*Licensed under the Academic.*\n+(\/\/\/\n)*/$replacement/;
	$txt2 =~ s/\/\/\/(.|[\n\r])*Yet Another(.|[\n\r])*Licensed under the Academic.*\n+(\/\/\/\n)*/$replacement/;
    }
    if (!($txt =~ /CopyPolicy/)) { 
	open(FOUT,">>license-changes.txt");
	print FOUT "$fname needs CopyPolicy added\n";
	close(FOUT);
    }
}


if ($txt ne $txt2) {
    open(FOUT,">$fname.shadow");
    print FOUT $txt2;
    close(FOUT);
    system "echo should have changed $fname >> license-changes.txt";
    #system "emacs $fname &";
} else {
#    system "echo \"$report $fname\" >> license-changes.txt";
}


