#!/bin/bash

# run as "./scripts/update-web-packages"

. ./scripts/config.sh

echo Updating website packages from local system

target=$WEB_SERVER

if [ "k$WEB_USER" = "k" ] ; then
    WEB_USER=`cat CVS/Root | sed "s/^:[^:]*://" | sed "s/[^a-z].*//"`
fi

echo USER is "$WEB_USER"

echo "Preparing local web package directory: web-package"
rm -rf web-package
mkdir -p web-package/debian
cp source-package/*.tar.gz source-package/*.zip web-package
ct=`find debian-package/archive -iname "*.deb" | wc --lines`
    # do we have both the stable and unstable packages?
if [ "k$ct" = "k2" ]; then
    cp -R debian-package/archive  web-package/debian/dists
    ln -s dists web-package/debian/archive
else
    echo DEBIAN PACKAGES NOT PRESENT
    sleep 2
fi

echo "Uploading to website download directory"
cd web-package && rsync --rsh="ssh -x -l $WEB_USER" --modify-window=2 -lauvzP . $target:$WEB_DOWNLOAD_DIR/yarp


