#!/bin/sh

# run as "./scripts/update-doc-manual"

## doxygen for pdf manual with links
doxygen conf/Doxyfile.min > /dev/null

# don't bother with this anymore
# doxygen for pdf manual with page numbers
# doxygen conf/Doxyfile.pagenum > /dev/null

base=$PWD

for manual in min; do

    cd $base/doc/$manual/latex

    ( perl -pe "s/\\\\doxyref\\{[^\\}]*\\}\\{p\\.\\}\\{([^\\}]*)\\}/\\\\hyperlink\\{\$1\\}/g" | perl -n -e "@b = (\$_ =~ /hyperlink\\{([^\\}]*)\\}/g ); print join(' ',@b), \"\\n\";" ) < manual.tex > order.txt
    order=`cat order.txt | egrep "[a-z]"`
    echo "ORDER is $order"
    echo -n > order.tex
    for f in $order; do
	echo "\\include{$f}" >> order.tex
    done

    # fix up unresolved links for material not included
    rm -f junk.tex
    for f in `ls *.tex`; do
	( 
	    perl -pe "s/\\\\hyperlink\\{\\}\\{([^\\}]*)\\}/\$1/g" | \
		perl -pe "s/p\\....pageref\\{\\}/see class docs/g" | \
		perl -pe "s/\\\\doxyref\\{([^\\}]*)\\}\\{p\\.\\}\\{\\}/\$1/g"|\
		perl -pe "s/(\\\\hypertarget\\{[^\\}]*\\}\\{\\})(.*)\\\\label\\{[^\\}]*\\}/\$2\$1/g" | \
		cat
	    ) < $f > junk.tex
	mv junk.tex $f
    done
    sed "/YARP Page/,/END/! { /YARP File/,/YARP Page/ s/^/%%/ }" -i refman.tex
    sed "s/.*section.YARP Page.*/%%\\0/" -i refman.tex
    sed "s/.*section.Welcome to YARP.*/%%\\0/" -i refman.tex
    sed "s/\\\\chapter.*/%%\\0/" -i refman.tex
    sed "s/.*input.index.*/%%\\0/" -i refman.tex
    sed "s/^.include.*/%%\\0/" -i refman.tex
    sed "s/^.input.*/%%\\0/" -i refman.tex
    sed "s/^%%.input.what_is_yarp.*/\\\\input\\{order\\}/" -i refman.tex
    perl -pe "s/(\\{tocdepth\\})\\{1\\}/\\{tocdepth\\}\\{2\\}/" < refman.tex > junk.tex
    mv junk.tex refman.tex
    for f in `ls *.tex`; do
	perl -pe "s/\\\\section/\\\\chapter/g" < $f > junk.tex
	perl -pe "s/(\\\\(sub)*)subsection/\${1}section/g" < junk.tex > $f
    done

    # certain lists are generated automatically, but have clumsy
    # formatting.  Here we patch that up.

    for f in group__dev__examples.tex; do
	sed "s/\\\\section.*Modules.*//" -i $f
	sed "s/\\\\section.Detailed.*//" -i $f
	( perl -n -e "@b = (\$_ =~ /hyperlink\\{([^\\}]*)\\}/g ); print join(' ',@b), \"\\n\";" ) < $f > order.txt
	order=`cat order.txt | egrep "[a-z]"`
	for g in $order; do
	    sed "s/\\\\chapter/\\\\section/" -i $g.tex
	    cat $g.tex >> $f
	done
    done
    

    make pdf
done
