#!/bin/bash

# run as "./scripts/update-web"

. ./scripts/config.sh

echo "Updating website (just main page) from local system"

target=$WEB_SERVER

if [ "k$WEB_USER" = "k" ] ; then
    WEB_USER=`cat CVS/Root | sed "s/^:[^:]*://" | sed "s/[^a-z].*//"`
fi

echo USER is "$WEB_USER"

cd doc && timeout 600 scp download.html index.html $WEB_USER@$target:$WEB_DOC_DIR



