#!/bin/bash

# run as "./scripts/update-web"

. ./scripts/config.sh

echo Updating website from local system

target=$WEB_SERVER

#if [ "k$WEB_USER" = "k" ] ; then
#    WEB_USER=`cat CVS/Root | sed "s/^:[^:]*://" | sed "s/[^a-z].*//"`
#fi

echo USER is "$WEB_USER"

cd doc && timeout 600 rsync --rsh="ssh -x -l $WEB_USER" --modify-window=2 -lauvzP . $target:$WEB_DOC_DIR



