#!/bin/sh

# run as "./scripts/update-doc"

# doxygen for man pages
doxygen conf/Doxyfile.man

# doxygen for normal user - omits some junk
rm -f doc/yarpdoc.zip
doxygen conf/Doxyfile.part > /dev/null
rm -rf tmpdoc
mkdir tmpdoc
cp -R doc/user/html tmpdoc/yarpdoc
cd tmpdoc
zip -r ../doc/yarpdoc.zip yarpdoc
cd ..
rm -rf tmpdoc

# doxygen with everything included
doxygen conf/Doxyfile > /dev/null

./scripts/update-doc-manual
