#!/bin/bash

. ./scripts/config.sh

if [ "`uname`" = "Linux" ]; then
	EXT="tar.gz"
	MGEN=""
	PGEN="-G TGZ"
else
	EXT="zip"
	MGEN="-G \"NMake Makefiles\""
	PGEN="-G ZIP"
fi


cd example/ace_check
rm -f CMakeCache.txt
sh -c "cmake $MGEN ."
rm -f *.$EXT
cpack $PGEN

if [ "k$WEB_USER" = "k" ] ; then
    WEB_USER=`cat CVS/Root | sed "s/^:[^:]*://" | sed "s/[^a-z].*//"`
fi

for f in `ls *.$EXT`; do
    echo Sending $f
    scp $f $WEB_USER@$WEB_SERVER:$WEB_DOWNLOAD_DIR/$f
done
