#!/bin/bash

# just an example; replace username "eshuy" to yours
# run from $YARP_ROOT/src/libYARP_OS2/
# as "./scripts/update-web"

echo Updating Sourceforge website from local system

target="yarp0.sourceforge.net"

if [ -e yarp-2.0.tar.gz ]; then
    cp yarp-2.0.tar.gz doc
else
    echo NO YARP install tar found
fi

cd doc && rsync --rsh="ssh -x -l eshuy" --modify-window=2 -lauvzP . $target:www/specs/dox

