#!/bin/bash

usernames=`svn log -q $1 | cut --delimiter="|" --fields 2 | grep -v "\-\-\-\-\-" | sort | uniq`

tmp="/tmp/who_wrote_usernames.txt"
tmp2="/tmp/who_wrote_names.txt"
tmp_unknown="/tmp/who_wrote_unknown.txt"

rm -f $tmp $tmp_unknown
problem=false
for username in $usernames; do
    echo "Svn author: $username"
    case $username in
	eshuy) echo "Paul Fitzpatrick" >> $tmp ;;
	pasa) echo "Giorgio Metta" >> $tmp ;;
	gmetta) echo "Giorgio Metta" >> $tmp ;;
	natta) echo "Lorenzo Natale" >> $tmp ;;
	agijsberts) echo "Arjan Gijsberts" >> $tmp ;;
	ale-scalzo) echo "Alessandro Scalzo" >> $tmp ;;
	alex_bernardino) echo "Alexandre Bernardino" >> $tmp ;;
	jru) echo "Jonas Ruesch" >> $tmp ;;
	spiglerg) echo "Giacomo Spigler" >> $tmp ;;
	assif) echo "Naeem Assif Mirza" >> $tmp ;;
	beltran) echo "Carlos Beltran" >> $tmp ;;
	claudio72) echo "Claudio Castellini" >> $tmp ;;
	emmebi75) echo "Matteo Brunettini" >> $tmp ;;
	francesco_nori) echo "Francesco Nori" >> $tmp ;;
	orfra) echo "Francesco Orabona" >> $tmp ;;
	pattacini) echo "Ugo Pattacini" >> $tmp ;;
	robuckot) echo "Michael Bucko" >> $tmp ;;

	babybot)
	echo "Paul Fitzpatrick" >> $tmp
	echo "Giorgio Metta" >> $tmp
	echo "Lorenzo Natale" >> $tmp
	;;

	*)
	echo "Unknown: $username" >> $tmp
	problem=true
	echo "$username" >> $tmp_unknown
	;;
    esac
done

# must have Lingua::EN::NameParse (apt-cache search nameparse | grep perl)
cat $tmp | sort | uniq | ./scripts/namesort | tee $tmp2

if $problem; then
    echo "NEED to fix:"
    cat $tmp_unknown
    exit 1
fi



