#!/bin/bash

echo "This script removes any non-current registrations"
echo "These can get left behind if processes crash"

for f in `yarp name list | sed "s/registration name //" | sed "s/ .*//" | sed "s/\\*//g" | grep -v "/quit" | grep -v "fallback" | grep -v "\\-\\-"`; do
	echo "Port $f"
	if yarp exists $f; then
	    echo "  it is ok"
	else
	    echo "  $f does not exist"
	    yarp name unregister $f
	fi
done


