#!/bin/bash

echo "This script removes any automatically-assigned registrations"
echo "These can get left behind if processes crash"

pattern="/tmp/port"

for f in `yarp name list | egrep "registration name $pattern" | sed "s/registration name //" | sed "s/ .*//"`; do
	echo "Port $f"
	yarp name unregister $f
done


