

SET(YARPDEV_NAMES "cuda")
SET(YARPDEV_WRAPPERS "None")
SET(YARPDEV_INCLUDES "CUDADeviceDriver.h")
SET(YARPDEV_TYPES "CUDAGPU")


IF (ENABLE_cuda)

	LINK_LIBRARIES(cudart cuda cutil GL)
	IF (NOT WINDOWS)
		LINK_LIBRARIES(GLEW)
	ENDIF (NOT WINDOWS)
ENDIF (ENABLE_cuda)
