#!/bin/bash

echo "Call as ./scripts/install-manpages"
echo ""
echo "Make sure you call ./scripts/make-manpages first"
echo "This is just for debian systems, when working from cvs repository"
echo "Otherwise manpages are in package"

sudo cp doc/man/man/man1/yarp* /usr/share/man/man1
sudo gzip /usr/share/man/man1/yarp*.1
