#!/bin/sh

echo Fixer for the eternal cross-editor formatting issue.
echo Make sure you run this as "./scripts/update-headers"

# reset change log
echo -n | tee indent-changes.txt

for f in `find . -iname "*.h" -size -100k; find . -iname "*.cpp"; find . -iname "*.c"`; do
    ignore=`echo "$f" | grep -q dd_orig && echo true || echo false`
    if $ignore ; then
	echo ignored $f >> indent-changes.txt
    else
	./scripts/update-header $f
    fi
done




