#!/bin/bash

# run as "./scripts/update-web"

. ./scripts/config.sh

echo Updating website from yarp-www

target=$WEB_SERVER

echo USER is "$WEB_USER"

mkdir -p yarp-www
cd yarp-www
if [ ! -e CVS ]; then
    cp -R ../CVS CVS
    echo "yarp-www" > CVS/Repository
    echo "" > CVS/Entries
fi
cvs update -d
timeout 600 rsync --rsh="ssh -x -l $WEB_USER" --modify-window=2 -lauvzP . $target:$WEB_DIR

