#!/bin/bash

# run as ./scripts/update-automake

# official YARP number is in $YARP_ROOT/conf/YarpVersion.cmake
version=`cat conf/YarpVersion.cmake | grep -v "#" | egrep --only-matching "[0-9]"`
version=`echo $version | sed 's/ /./g'`


# update source lists in Makefile.am files
for f in `find src -iname "Makefile.am"`; do
	echo Scanning $f
	dir=`dirname $f`
	grep -q "automake_expand" $f && (
		./scripts/update-automake-single $dir < $f > tmp.am
		cmp $f tmp.am || ( 
			echo "  Modified $f"
			cp tmp.am $f
		)
	)
done


# update yarp version number
for f in `find . -iname "configure.ac"`; do
    echo Scanning $f
    dir=`dirname $f`
    grep -q "AC_INIT" $f && (
	sed "s/AC_INIT(yarp, [^,]*/AC_INIT(yarp, $version/" < $f > tmp.ac
	cmp $f tmp.ac || ( 
	    echo "  Modified $f"
	    cp tmp.ac $f
	)
    )
done

echo "YARP version is $version"
