/*
 * SPDX-FileCopyrightText: 2006-2021 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: BSD-3-Clause
 */

// Autogenerated by Thrift Compiler (0.14.1-yarped)
//
// This is an automatically generated file.
// It could get re-generated if the ALLOW_IDL_GENERATION flag is on.

#include <return_getDistanceRange.h>

// Constructor with field values
return_getDistanceRange::return_getDistanceRange(const yarp::dev::ReturnValue& retval,
                                                 const double min,
                                                 const double max) :
        WirePortable(),
        retval(retval),
        min(min),
        max(max)
{
}

// Read structure on a Wire
bool return_getDistanceRange::read(yarp::os::idl::WireReader& reader)
{
    if (!nested_read_retval(reader)) {
        return false;
    }
    if (!read_min(reader)) {
        return false;
    }
    if (!read_max(reader)) {
        return false;
    }
    if (reader.isError()) {
        return false;
    }
    return true;
}

// Read structure on a Connection
bool return_getDistanceRange::read(yarp::os::ConnectionReader& connection)
{
    yarp::os::idl::WireReader reader(connection);
    if (!reader.readListHeader(3)) {
        return false;
    }
    if (!read(reader)) {
        return false;
    }
    return true;
}

// Write structure on a Wire
bool return_getDistanceRange::write(const yarp::os::idl::WireWriter& writer) const
{
    if (!nested_write_retval(writer)) {
        return false;
    }
    if (!write_min(writer)) {
        return false;
    }
    if (!write_max(writer)) {
        return false;
    }
    if (writer.isError()) {
        return false;
    }
    return true;
}

// Write structure on a Connection
bool return_getDistanceRange::write(yarp::os::ConnectionWriter& connection) const
{
    yarp::os::idl::WireWriter writer(connection);
    if (!writer.writeListHeader(3)) {
        return false;
    }
    if (!write(writer)) {
        return false;
    }
    return true;
}

// Convert to a printable string
std::string return_getDistanceRange::toString() const
{
    yarp::os::Bottle b;
    if (!yarp::os::Portable::copyPortable(*this, b)) {
        return {};
    }
    return b.toString();
}

// read retval field
bool return_getDistanceRange::read_retval(yarp::os::idl::WireReader& reader)
{
    if (reader.noMore()) {
        reader.fail();
        return false;
    }
    if (!reader.read(retval)) {
        reader.fail();
        return false;
    }
    return true;
}

// write retval field
bool return_getDistanceRange::write_retval(const yarp::os::idl::WireWriter& writer) const
{
    if (!writer.write(retval)) {
        return false;
    }
    return true;
}

// read (nested) retval field
bool return_getDistanceRange::nested_read_retval(yarp::os::idl::WireReader& reader)
{
    if (reader.noMore()) {
        reader.fail();
        return false;
    }
    if (!reader.readNested(retval)) {
        reader.fail();
        return false;
    }
    return true;
}

// write (nested) retval field
bool return_getDistanceRange::nested_write_retval(const yarp::os::idl::WireWriter& writer) const
{
    if (!writer.writeNested(retval)) {
        return false;
    }
    return true;
}

// read min field
bool return_getDistanceRange::read_min(yarp::os::idl::WireReader& reader)
{
    if (reader.noMore()) {
        reader.fail();
        return false;
    }
    if (!reader.readFloat64(min)) {
        reader.fail();
        return false;
    }
    return true;
}

// write min field
bool return_getDistanceRange::write_min(const yarp::os::idl::WireWriter& writer) const
{
    if (!writer.writeFloat64(min)) {
        return false;
    }
    return true;
}

// read (nested) min field
bool return_getDistanceRange::nested_read_min(yarp::os::idl::WireReader& reader)
{
    if (reader.noMore()) {
        reader.fail();
        return false;
    }
    if (!reader.readFloat64(min)) {
        reader.fail();
        return false;
    }
    return true;
}

// write (nested) min field
bool return_getDistanceRange::nested_write_min(const yarp::os::idl::WireWriter& writer) const
{
    if (!writer.writeFloat64(min)) {
        return false;
    }
    return true;
}

// read max field
bool return_getDistanceRange::read_max(yarp::os::idl::WireReader& reader)
{
    if (reader.noMore()) {
        reader.fail();
        return false;
    }
    if (!reader.readFloat64(max)) {
        reader.fail();
        return false;
    }
    return true;
}

// write max field
bool return_getDistanceRange::write_max(const yarp::os::idl::WireWriter& writer) const
{
    if (!writer.writeFloat64(max)) {
        return false;
    }
    return true;
}

// read (nested) max field
bool return_getDistanceRange::nested_read_max(yarp::os::idl::WireReader& reader)
{
    if (reader.noMore()) {
        reader.fail();
        return false;
    }
    if (!reader.readFloat64(max)) {
        reader.fail();
        return false;
    }
    return true;
}

// write (nested) max field
bool return_getDistanceRange::nested_write_max(const yarp::os::idl::WireWriter& writer) const
{
    if (!writer.writeFloat64(max)) {
        return false;
    }
    return true;
}
